from pathlib import Path
p=Path('delivery-dashboard.html')
s=p.read_text(encoding='utf-8')
old="async function loadDeliveryOrders(searchOverride=null){ordersGrid.innerHTML='<div class=\"loading\">جاري تحميل الشحنات...</div>';try{const sb=await getDeliverySb(),term=cleanSearch(searchOverride===null?deliverySearch.value:searchOverride);let q=sb.from('orders').select('*');if(term){const p='%'+term+'%';q=q.or(`order_code.ilike.${p},reference_order_no.ilike.${p},customer_name.ilike.${p},customer_phone.ilike.${p}`)}const{data,error}=await q.order('created_at',{ascending:false}).limit(10000);if(error)throw error;const scoped=(data||[]).filter(o=>orderBelongsToCourier(o)&&orderBelongsToBranch(o)),filtered=scoped.filter(o=>tabForOrder(o)===deliveryTab);deliveryTotal=filtered.length;const from=(deliveryPage-1)*deliveryPageSize;deliveryOrders=filtered.slice(from,from+deliveryPageSize);await enrichCustomers(deliveryOrders);ordersGrid.innerHTML=deliveryOrders.map(renderOrderCard).join('')||'<div class=\"empty\">لا توجد شحنات في هذا القسم.</div>';renderPager();await Promise.all([loadDeliveryCounts(),loadFinance()])}catch(error){console.error('Delivery orders error:',error);ordersGrid.innerHTML=`<div class=\"error\">${esc(error.message||error)}</div>`}}"
new="async function loadDeliveryOrders(searchOverride=null){ordersGrid.innerHTML='<div class=\"loading\">جاري تحميل الشحنات...</div>';try{const sb=await getDeliverySb(),term=cleanSearch(searchOverride===null?deliverySearch.value:searchOverride);let q=sb.from('orders').select('*');if(term){const p='%'+term+'%';q=q.or(`order_code.ilike.${p},reference_order_no.ilike.${p},customer_name.ilike.${p},customer_phone.ilike.${p}`)}const{data,error}=await q.order('created_at',{ascending:false}).limit(10000);if(error)throw error;const scoped=(data||[]).filter(o=>orderBelongsToCourier(o)&&orderBelongsToBranch(o)),filtered=term?scoped:scoped.filter(o=>tabForOrder(o)===deliveryTab);deliveryTotal=filtered.length;const from=(deliveryPage-1)*deliveryPageSize;deliveryOrders=filtered.slice(from,from+deliveryPageSize);await enrichCustomers(deliveryOrders);ordersGrid.innerHTML=deliveryOrders.map(renderOrderCard).join('')||(term?'<div class=\"empty\">لا توجد شحنة مطابقة للبحث في جميع الحالات.</div>':'<div class=\"empty\">لا توجد شحنات في هذا القسم.</div>');renderPager();await Promise.all([loadDeliveryCounts(),loadFinance()])}catch(error){console.error('Delivery orders error:',error);ordersGrid.innerHTML=`<div class=\"error\">${esc(error.message||error)}</div>`}}"
if old not in s:
    raise SystemExit('loadDeliveryOrders target not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
