from pathlib import Path

employee = r'''
<style>
/* VERTICAL_STATUS_SIDEBAR_V1 */
#pipelineTabs{display:flex;flex-direction:column;gap:5px;width:255px;float:right;position:sticky;top:12px;max-height:calc(100vh - 24px);overflow:auto;background:#f8fafc;border:1px solid #dbe4ee;border-radius:14px;padding:10px;margin:0 0 18px 16px;box-shadow:0 5px 18px #0f172a12;scrollbar-width:thin}
#pipelineTabs .pipeline-tab{width:100%;display:flex;align-items:center;justify-content:space-between;text-align:right;border-radius:9px;padding:9px 11px;box-shadow:none;white-space:normal;min-height:40px}
#pipelineTabs .pipeline-tab:hover{background:#eef6ff;border-color:#93c5fd}
#pipelineTabs .pipeline-tab.active{background:#1f4f78;color:#fff;border-color:#1f4f78}
#pipelineTabs .pipeline-count{margin-right:auto;margin-left:0;flex:0 0 auto}
.status-sidebar-title{font-size:14px;font-weight:900;color:#0f2f4f;padding:5px 6px 10px;border-bottom:1px solid #dbe4ee;margin-bottom:3px}
.status-group-title{font-size:11px;font-weight:900;color:#64748b;padding:10px 7px 5px;margin-top:2px}
#ordersPanel,#rewardPanel{margin-right:272px;min-height:420px}.container::after{content:"";display:block;clear:both}
@media(max-width:980px){#pipelineTabs{float:none;position:static;width:100%;max-height:none;margin:0 0 12px 0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.status-sidebar-title,.status-group-title{grid-column:1/-1}#ordersPanel,#rewardPanel{margin-right:0}}
@media(max-width:600px){#pipelineTabs{grid-template-columns:1fr}}
</style>
<script>
/* VERTICAL_STATUS_SIDEBAR_V1 */
Object.keys(PIPELINES).forEach(k=>delete PIPELINES[k]);
Object.assign(PIPELINES,{all:{label:'🌐 كل الطلبات',all:true},waiting_employee:{label:'📩 انتظار رد الموظف',statuses:['انتظار رد الموظف']},waiting_customer:{label:'⏳ بانتظار موافقة العميل',statuses:['بانتظار موافقة العميل','بانتظار موافقة الزبون','بانتظار التسعير','تم التسعير / بانتظار موافقة العميل']},in_order:{label:'🔄 قيد الطلب',statuses:['قيد الطلب']},company_store:{label:'🏬 مخزن الشركة',statuses:['مخزن شركة']},branch:{label:'🏢 محولة إلى الفرع',branch:true,statuses:['تجهيز شحن','مخزن محلي']},shipped:{label:'🚚 تم الشحن',statuses:['تم الشحن']},courier:{label:'🛵 مندوب',statuses:['مندوب']},internal_distribution:{label:'📍 توزيع داخلي',statuses:['توزيع داخلي']},waiting_payment:{label:'💳 بانتظار تأكيد الدفع',statuses:['تمت الموافقة - بانتظار الدفع','تمت الموافقة']},paid:{label:'💰 تم التسديد',statuses:['تم التسديد']},delivered:{label:'✅ تم التسليم',statuses:['تم التسليم']},cancelled:{label:'🚫 ملغية من قبل العميل',statuses:['ملغي من قبل العميل']},rejected:{label:'❌ رفض / مرفوض',statuses:['رفض الطلب','مرفوض']},rewards:{label:'🎁 مستحق مكافأة',rewards:true}});
const EMPLOYEE_STATUS_GROUPS=[{title:'🌐 عرض شامل',keys:['all']},{title:'📦 الطلبات النشطة وقيد المعالجة',keys:['waiting_employee','waiting_customer','in_order','company_store','branch','shipped','courier','internal_distribution']},{title:'✅ الطلبات المكتملة والمالية',keys:['waiting_payment','paid','delivered']},{title:'❌ الطلبات الملغاة والمرفوضة',keys:['cancelled','rejected']},{title:'🎁 المكافآت',keys:['rewards']}];
renderPipelineTabs=function(){const box=document.getElementById('pipelineTabs');if(!box)return;let html='<div class="status-sidebar-title">حالات الطلبات</div>';EMPLOYEE_STATUS_GROUPS.forEach(g=>{html+=`<div class="status-group-title">${g.title}</div>`;g.keys.forEach(k=>{const p=PIPELINES[k];if(p)html+=`<button class="pipeline-tab ${k===activePipeline?'active':''}" data-pipeline="${k}" onclick="switchPipeline('${k}')"><span>${p.label}</span><span id="count-${k}" class="pipeline-count">${globalPipelineCounts[k]??0}</span></button>`})});box.innerHTML=html};
buildPipelineQuery=function(sb,count=false){const p=PIPELINES[activePipeline],term=normalizeSearch(document.getElementById('employeeOrderSearch')?.value||'');let q=sb.from('orders').select('*',count?{count:'exact'}:{});if(!p.all){if(p.branch){q=q.in('status',p.statuses).or('branch_id.not.is.null,branch_name.not.is.null');const branch=cloudId(document.getElementById('branchFilter')?.value);if(branch)q=q.eq('branch_id',branch)}else if(Array.isArray(p.statuses)&&p.statuses.length)q=q.in('status',p.statuses)}if(term){const pat=`%${term}%`;q=q.or(`order_code.ilike.${pat},reference_order_no.ilike.${pat},customer_name.ilike.${pat},customer_phone.ilike.${pat}`)}return q};
refreshPipelineCounts=async function(){try{const{customers,orders,by}=await employeeRewardDataset(),next={};Object.entries(PIPELINES).forEach(([k,p])=>{if(p.all){next[k]=orders.length;return}if(p.rewards){next[k]=customers.filter(c=>employeeRewardCycle(c,by.get(cloudId(c.id))||[]).length>=EMPLOYEE_REWARD_TARGET).length;return}if(p.branch){next[k]=orders.filter(o=>(p.statuses||[]).includes(o.status)&&(cloudId(o.branch_id)||String(o.branch_name||'').trim())).length;return}next[k]=orders.filter(o=>(p.statuses||[]).includes(o.status)).length});globalPipelineCounts=next;Object.entries(next).forEach(([k,n])=>{const el=document.getElementById('count-'+k);if(el)el.innerText=n})}catch(e){console.error('Vertical sidebar counters error:',e)}};
const employeeStatusInitBase=window.onload;window.onload=async function(...args){if(typeof employeeStatusInitBase==='function')await employeeStatusInitBase.apply(this,args);renderPipelineTabs();setActivePipelineButton(activePipeline);await refreshPipelineCounts()};Object.assign(window,{renderPipelineTabs,refreshPipelineCounts});
</script>
'''

admin = r'''
<style>
/* VERTICAL_STATUS_SIDEBAR_V1 */
#adminPipelineTabs{display:flex;flex-direction:column;gap:5px;width:255px;float:right;position:sticky;top:12px;max-height:calc(100vh - 24px);overflow:auto;background:#f8fafc;border:1px solid #dbe4ee;border-radius:14px;padding:10px;margin:0 0 18px 16px;box-shadow:0 5px 18px #0f172a12;scrollbar-width:thin}
#adminPipelineTabs .pipeline-tab{width:100%;display:flex;align-items:center;justify-content:space-between;text-align:right;border-radius:9px;padding:9px 11px;box-shadow:none;white-space:normal;min-height:40px}
#adminPipelineTabs .pipeline-tab:hover{background:#eef6ff;border-color:#93c5fd}#adminPipelineTabs .pipeline-tab.active{background:#1f4f78;color:#fff;border-color:#1f4f78}#adminPipelineTabs .pipeline-count{margin-right:auto;margin-left:0;flex:0 0 auto}
.admin-status-sidebar-title{font-size:14px;font-weight:900;color:#0f2f4f;padding:5px 6px 10px;border-bottom:1px solid #dbe4ee;margin-bottom:3px}.admin-status-group-title{font-size:11px;font-weight:900;color:#64748b;padding:10px 7px 5px;margin-top:2px}
#ordersListPanel,#adminRewardPanel{margin-right:272px;min-height:420px}#orders.card::after{content:"";display:block;clear:both}
@media(max-width:1050px){#adminPipelineTabs{float:none;position:static;width:100%;max-height:none;margin:0 0 12px 0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.admin-status-sidebar-title,.admin-status-group-title{grid-column:1/-1}#ordersListPanel,#adminRewardPanel{margin-right:0}}@media(max-width:600px){#adminPipelineTabs{grid-template-columns:1fr}}
</style>
<script>
/* VERTICAL_STATUS_SIDEBAR_V1 */
Object.keys(ADMIN_PIPELINES).forEach(k=>delete ADMIN_PIPELINES[k]);
Object.assign(ADMIN_PIPELINES,{all:{label:'🌐 كل الطلبات',all:true},waiting_employee:{label:'📩 انتظار رد الموظف',statuses:['انتظار رد الموظف']},waiting_customer:{label:'⏳ بانتظار موافقة العميل',statuses:['بانتظار موافقة العميل','بانتظار موافقة الزبون','بانتظار التسعير','تم التسعير / بانتظار موافقة العميل']},in_order:{label:'🔄 قيد الطلب',statuses:['قيد الطلب']},company_store:{label:'🏬 مخزن الشركة',statuses:['مخزن شركة']},branch:{label:'🏢 محولة إلى الفرع',branch:true,statuses:['تجهيز شحن','مخزن محلي']},shipped:{label:'🚚 تم الشحن',statuses:['تم الشحن']},courier:{label:'🛵 مندوب',statuses:['مندوب']},internal_distribution:{label:'📍 توزيع داخلي',statuses:['توزيع داخلي']},waiting_payment:{label:'💳 بانتظار تأكيد الدفع',statuses:['تمت الموافقة - بانتظار الدفع','تمت الموافقة']},paid:{label:'💰 تم التسديد',statuses:['تم التسديد']},delivered:{label:'✅ تم التسليم',statuses:['تم التسليم']},cancelled:{label:'🚫 ملغية من قبل العميل',statuses:['ملغي من قبل العميل']},rejected:{label:'❌ رفض / مرفوض',statuses:['رفض الطلب','مرفوض']},rewards:{label:'🎁 مستحق مكافأة',rewards:true}});
const ADMIN_STATUS_GROUPS=[{title:'🌐 عرض شامل',keys:['all']},{title:'📦 الطلبات النشطة وقيد المعالجة',keys:['waiting_employee','waiting_customer','in_order','company_store','branch','shipped','courier','internal_distribution']},{title:'✅ الطلبات المكتملة والمالية',keys:['waiting_payment','paid','delivered']},{title:'❌ الطلبات الملغاة والمرفوضة',keys:['cancelled','rejected']},{title:'🎁 المكافآت',keys:['rewards']}];
renderAdminPipelineTabs=function(){const box=document.getElementById('adminPipelineTabs');if(!box)return;let html='<div class="admin-status-sidebar-title">حالات الطلبات</div>';ADMIN_STATUS_GROUPS.forEach(g=>{html+=`<div class="admin-status-group-title">${g.title}</div>`;g.keys.forEach(k=>{const p=ADMIN_PIPELINES[k];if(p)html+=`<button class="pipeline-tab ${k===activeAdminPipeline?'active':''}" data-pipeline="${k}" onclick="switchAdminPipeline('${k}')"><span>${p.label}</span><span id="admin-count-${k}" class="pipeline-count">${globalAdminPipelineCounts[k]??0}</span></button>`})});box.innerHTML=html};
refreshAdminPipelineCounts=async function(){try{const{customers,orders,by}=await adminRewardDataset(),next={};Object.entries(ADMIN_PIPELINES).forEach(([k,p])=>{if(p.all){next[k]=orders.length;return}if(p.rewards){next[k]=customers.filter(c=>adminRewardCycleOf(c,by.get(String(c.id))||[]).length>=ADMIN_REWARD_TARGET).length;return}if(p.branch){next[k]=orders.filter(o=>(p.statuses||[]).includes(o.status)&&(String(o.branch_id||'').trim()||String(o.branch_name||'').trim())).length;return}next[k]=orders.filter(o=>(p.statuses||[]).includes(o.status)).length});globalAdminPipelineCounts=next;Object.entries(next).forEach(([k,n])=>{const el=document.getElementById('admin-count-'+k);if(el)el.innerText=n})}catch(e){console.error('Vertical admin sidebar counters error:',e)}};
loadAdminOrders=async function(){const p=ADMIN_PIPELINES[activeAdminPipeline];if(p.rewards)return;const body=document.getElementById('adminOrdersTableBody');body.innerHTML='<tr><td colspan="9">جاري التحميل...</td></tr>';const rid=++orderSearchRequestId;try{const sb=await ensureCustomerSupabase(),term=searchTerm(document.getElementById('orderSearchInput')?.value||'');let customerIds=[];if(term){const pat=`%${term}%`,{data}=await sb.from('customers').select('id').or(`name.ilike.${pat},phone.ilike.${pat},secondary_phone.ilike.${pat},code.ilike.${pat},email.ilike.${pat}`).limit(500);customerIds=(data||[]).map(x=>x.id)}let q=sb.from('orders').select('*',{count:'exact'});if(!p.all){if(p.branch){q=q.in('status',p.statuses).or('branch_id.not.is.null,branch_name.not.is.null');const bid=document.getElementById('adminBranchFilter').value;if(bid)q=q.eq('branch_id',bid)}else if(Array.isArray(p.statuses)&&p.statuses.length)q=q.in('status',p.statuses)}if(term){const pat=`%${term}%`,ors=[`order_code.ilike.${pat}`,`reference_order_no.ilike.${pat}`,`customer_name.ilike.${pat}`,`customer_phone.ilike.${pat}`];if(customerIds.length)ors.push(`customer_id.in.(${customerIds.join(',')})`);q=q.or(ors.join(','))}const from=(orderPage-1)*orderPageSize,{data,error,count}=await q.order('created_at',{ascending:false}).range(from,from+orderPageSize-1);if(rid!==orderSearchRequestId)return;if(error)throw error;orderTotal=count||0;adminOrdersCloud=(data||[]).map(normalizeAdminOrderMetrics);await enrichCustomerCodes(adminOrdersCloud);body.innerHTML='';adminOrdersCloud.forEach(o=>body.innerHTML+=adminOrderRow(o));if(!body.innerHTML)body.innerHTML='<tr><td colspan="9">لا توجد طلبات في هذا القسم.</td></tr>';renderOrderPagination();await renderAdminBarcodes()}catch(e){console.error('Admin sidebar orders load error:',e);body.innerHTML=`<tr><td colspan="9" style="color:red">${esc(e.message||e)}</td></tr>`}};
const adminStatusInitBase=initAdminDashboard;initAdminDashboard=async function(){await adminStatusInitBase();renderAdminPipelineTabs();setActiveAdminPipelineButton(activeAdminPipeline);await refreshAdminPipelineCounts()};Object.assign(window,{renderAdminPipelineTabs,refreshAdminPipelineCounts,loadAdminOrders});
</script>
'''

for path,block in [('employee-dashboard.html',employee),('admin-dashboard.html',admin)]:
    p=Path(path)
    s=p.read_text(encoding='utf-8')
    if 'VERTICAL_STATUS_SIDEBAR_V1' not in s:
        p.write_text(s+'\n'+block,encoding='utf-8')
