from pathlib import Path

p=Path('delivery-dashboard.html')
s=p.read_text(encoding='utf-8')
s=s.replace("const DELIVERY_TABS={active:['جاري التوصيل مع المندوب','مندوب','توزيع داخلي'],delivered:['تم التسليم'],deferred:['مؤجل'],rejected:['رفض الطلب','مرفوض','تم رفض الطلب أو عدم التسليم','راجع']};", "const DELIVERY_TABS={active:['جاري التوصيل مع المندوب','مندوب','توزيع داخلي'],delivered:['تم التسليم'],deferred:[],rejected:['رفض التسليم','رفض الطلب','مرفوض']};")
s=s.replace("function tabForOrder(o){const s=String(o.status||'');for(const[k,list]of Object.entries(DELIVERY_TABS))if(list.includes(s))return k;return'active'}", "function tabForOrder(o){const s=String(o.status||''),d=parseDetails(o.details);if(s==='تم التسليم')return'delivered';if(DELIVERY_TABS.rejected.includes(s))return'rejected';if(d.delivery_state==='deferred'||d.delivery_deferred_until)return'deferred';return'active'}")
s=s.replace("function statusOptions(tab,current){const sets={active:['جاري التوصيل مع المندوب','مندوب','توزيع داخلي'],delivered:['تم التسليم'],deferred:['مؤجل'],rejected:['رفض الطلب','مرفوض','راجع']};return [...new Set([current,...Object.values(sets).flat()])].filter(Boolean).map(s=>`<option value=\"${esc(s)}\" ${s===current?'selected':''}>${esc(s)}</option>`).join('')}", "function statusOptions(tab,current,details={}){const deferred=details.delivery_state==='deferred'||!!details.delivery_deferred_until,sets=['مندوب','توزيع داخلي','تم التسليم','رفض التسليم','مرفوض'];const values=[...new Set([current,...sets])].filter(Boolean);return `<option value=\"__deferred__\" ${deferred?'selected':''}>مؤجل</option>`+values.map(s=>`<option value=\"${esc(s)}\" ${!deferred&&s===current?'selected':''}>${esc(s)}</option>`).join('')}")
s=s.replace("${statusOptions(deliveryTab,o.status)}", "${statusOptions(deliveryTab,o.status,d)}")
s=s.replace("<textarea id=\"note-${id}\" placeholder=\"ملاحظة التأجيل / التوصيل\">${esc(note)}</textarea><input class=\"full\" id=\"reason-${id}\"", "<textarea id=\"note-${id}\" placeholder=\"ملاحظة التأجيل / التوصيل\">${esc(note)}</textarea><select id=\"rating-${id}\" class=\"full\"><option value=\"\">تقييم تجربة التسليم</option>${[1,2,3,4,5].map(n=>`<option value=\"${n}\" ${Number(d.delivery_rating||0)===n?'selected':''}>${'⭐'.repeat(n)} (${n}/5)</option>`).join('')}</select><input class=\"full\" id=\"reason-${id}\"")
s=s.replace("const s=document.getElementById('st-'+id)?.value||'';document.getElementById('defer-'+id).style.display=s==='مؤجل'?'block':'none';document.getElementById('reason-'+id).style.display=DELIVERY_TABS.rejected.includes(s)?'block':'none'", "const s=document.getElementById('st-'+id)?.value||'';document.getElementById('defer-'+id).style.display=s==='__deferred__'?'block':'none';document.getElementById('reason-'+id).style.display=DELIVERY_TABS.rejected.includes(s)?'block':'none'")
s=s.replace("select('status').eq('courier_id'", "select('status,details').eq('courier_id'")
old="async function loadDeliveryOrders(searchOverride=null){ordersGrid.innerHTML='<div class=\"loading\">جاري تحميل الشحنات...</div>';const sb=await getDeliverySb(),from=(deliveryPage-1)*deliveryPageSize,term=cleanSearch(searchOverride===null?deliverySearch.value:searchOverride),statuses=DELIVERY_TABS[deliveryTab];let q=sb.from('orders').select('*',{count:'exact'}).eq('courier_id',idText(currentCourier.id)).eq('branch_id',idText(currentCourier.branch_id)).in('status',statuses);if(term){const p='%'+term+'%';q=q.or(`order_code.ilike.${p},reference_order_no.ilike.${p},customer_name.ilike.${p},customer_phone.ilike.${p}`)}const{data,error,count}=await q.order('created_at',{ascending:false}).range(from,from+deliveryPageSize-1);if(error){ordersGrid.innerHTML=`<div class=\"error\">${esc(error.message)}</div>`;return}deliveryOrders=data||[];await enrichCustomers(deliveryOrders);deliveryTotal=count||0;ordersGrid.innerHTML=deliveryOrders.map(renderOrderCard).join('')||'<div class=\"empty\">لا توجد شحنات في هذا القسم.</div>';renderPager();await Promise.all([loadDeliveryCounts(),loadFinance()])}"
new="async function loadDeliveryOrders(searchOverride=null){ordersGrid.innerHTML='<div class=\"loading\">جاري تحميل الشحنات...</div>';const sb=await getDeliverySb(),term=cleanSearch(searchOverride===null?deliverySearch.value:searchOverride);let q=sb.from('orders').select('*').eq('courier_id',idText(currentCourier.id)).eq('branch_id',idText(currentCourier.branch_id));if(term){const p='%'+term+'%';q=q.or(`order_code.ilike.${p},reference_order_no.ilike.${p},customer_name.ilike.${p},customer_phone.ilike.${p}`)}const{data,error}=await q.order('created_at',{ascending:false}).limit(10000);if(error){ordersGrid.innerHTML=`<div class=\"error\">${esc(error.message)}</div>`;return}const filtered=(data||[]).filter(o=>tabForOrder(o)===deliveryTab);deliveryTotal=filtered.length;const from=(deliveryPage-1)*deliveryPageSize;deliveryOrders=filtered.slice(from,from+deliveryPageSize);await enrichCustomers(deliveryOrders);ordersGrid.innerHTML=deliveryOrders.map(renderOrderCard).join('')||'<div class=\"empty\">لا توجد شحنات في هذا القسم.</div>';renderPager();await Promise.all([loadDeliveryCounts(),loadFinance()])}"
if old not in s: raise SystemExit('loadDeliveryOrders target not found')
s=s.replace(old,new)
old="async function saveDeliveryOrder(encodedId){const id=decodeURIComponent(encodedId),o=deliveryOrders.find(x=>idText(x.id)===idText(id));if(!o)return;const status=document.getElementById('st-'+encodedId).value,defer=document.getElementById('defer-'+encodedId).value,note=document.getElementById('note-'+encodedId).value.trim(),reason=document.getElementById('reason-'+encodedId).value.trim();if(status==='مؤجل'&&!defer)return alert('حدد تاريخ التأجيل.');if(DELIVERY_TABS.rejected.includes(status)&&!reason)return alert('اكتب سبب الرفض أو الراجع.');const details=parseDetails(o.details);details.delivery_deferred_until=status==='مؤجل'?defer:null;details.delivery_note=note||null;details.delivery_rejection_reason=DELIVERY_TABS.rejected.includes(status)?reason:null;details.delivery_updated_at=new Date().toISOString();const payload={status,details,rejection_reason:DELIVERY_TABS.rejected.includes(status)?reason:null};const sb=await getDeliverySb(),{error}=await sb.from('orders').update(payload).eq('id',id).eq('courier_id',idText(currentCourier.id));if(error)return alert('تعذر تحديث الشحنة: '+error.message);alert('تم تحديث حالة الشحنة بنجاح.');await loadDeliveryOrders()}"
new="async function saveDeliveryOrder(encodedId){const id=decodeURIComponent(encodedId),o=deliveryOrders.find(x=>idText(x.id)===idText(id));if(!o)return;const selected=document.getElementById('st-'+encodedId).value,defer=document.getElementById('defer-'+encodedId).value,note=document.getElementById('note-'+encodedId).value.trim(),reason=document.getElementById('reason-'+encodedId).value.trim(),rating=Number(document.getElementById('rating-'+encodedId)?.value||0),isDeferred=selected==='__deferred__',status=isDeferred?(DELIVERY_TABS.active.includes(o.status)?o.status:'مندوب'):selected;if(isDeferred&&!defer)return alert('حدد تاريخ التأجيل.');if(DELIVERY_TABS.rejected.includes(status)&&!reason)return alert('اكتب سبب الرفض أو الراجع.');const details=parseDetails(o.details);details.delivery_state=isDeferred?'deferred':null;details.delivery_deferred_until=isDeferred?defer:null;details.delivery_note=note||null;details.delivery_rejection_reason=DELIVERY_TABS.rejected.includes(status)?reason:null;details.delivery_rating=rating>=1&&rating<=5?rating:null;details.delivery_updated_at=new Date().toISOString();const payload={status,details,rejection_reason:DELIVERY_TABS.rejected.includes(status)?reason:null};const sb=await getDeliverySb(),{error}=await sb.from('orders').update(payload).eq('id',id).eq('courier_id',idText(currentCourier.id));if(error)return alert('تعذر تحديث الشحنة: '+error.message);alert('تم تحديث حالة الشحنة بنجاح.');await loadDeliveryOrders()}"
if old not in s: raise SystemExit('saveDeliveryOrder target not found')
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')

b=Path('branch-dashboard.html')
s=b.read_text(encoding='utf-8')
needle='<div><button class="purple" onclick="openSettlementHistoryModal()">📜 سجل التقفيلات</button> <button class="orange" onclick="requestBranchSettlement()">💰 طلب تقفيل عهدة الفرع</button> <a href="login.html" class="btn red">تسجيل الخروج</a></div>'
replacement='<div><a id="deliveryReportsLink" class="btn blue" href="admin-delivery-reports.html">📊 تقارير وتصفية المندوبين</a> <button class="purple" onclick="openSettlementHistoryModal()">📜 سجل التقفيلات</button> <button class="orange" onclick="requestBranchSettlement()">💰 طلب تقفيل عهدة الفرع</button> <a href="login.html" class="btn red">تسجيل الخروج</a></div>'
if needle not in s: raise SystemExit('branch top target not found')
s=s.replace(needle,replacement,1)
s += '''\n<script>\n/* DELIVERY_REPORT_LINK_V1 */\n(function(){function bindDeliveryReportLink(){const a=document.getElementById('deliveryReportsLink'),id=new URLSearchParams(location.search).get('branchId')||'';if(a&&id)a.href='admin-delivery-reports.html?branchId='+encodeURIComponent(id)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindDeliveryReportLink);else bindDeliveryReportLink()})();\n</script>\n'''
b.write_text(s,encoding='utf-8')
