from pathlib import Path
import re

def req(s, old, new, label):
    if old not in s:
        raise SystemExit(f'Missing block: {label}')
    return s.replace(old,new,1)

# delivery-dashboard.html
p=Path('delivery-dashboard.html'); s=p.read_text(encoding='utf-8')
s=req(s,
"function idText(v){return v==null?'':String(v).trim()}\nfunction params(){return new URLSearchParams(location.search)}",
"function idText(v){return v==null?'':String(v).trim()}\nfunction isUuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(idText(v))}\nfunction firstUuid(obj,fields){for(const k of fields){const v=idText(obj?.[k]);if(isUuid(v))return v}return''}\nfunction params(){return new URLSearchParams(location.search)}",
'delivery uuid helpers')
old="async function verifyCourier(){const courierId=courierIdFromUrl(),branchId=branchIdFromUrl();if(!courierId||!branchId)throw new Error('رابط لوحة المندوب غير مكتمل. سجّل الدخول من جديد.');const sb=await getDeliverySb(),{data,error}=await sb.from('couriers').select('*').eq('id',courierId).eq('branch_id',branchId).maybeSingle();if(error)throw error;if(!data)throw new Error('تعذر التحقق من حساب المندوب في Supabase.');if(data.is_active===false||data.active===false||data.disabled===true)throw new Error('حساب المندوب معطل.');currentCourier=data;const br=await sb.from('branches').select('*').eq('id',branchId).maybeSingle();if(!br.error)currentBranch=br.data||null;history.replaceState(null,'','delivery-dashboard.html?courierId='+encodeURIComponent(idText(data.id))+'&branchId='+encodeURIComponent(idText(data.branch_id)));deliveryTitle.textContent='لوحة موظف التوصيل: '+(data.name||data.phone||data.id);identityMeta.textContent='الفرع: '+(currentBranch?.name||currentBranch?.branch_name||data.branch_id)+' — '+(data.phone||'')}"
new="async function verifyCourier(){const courierHint=courierIdFromUrl(),branchHint=branchIdFromUrl();if(!courierHint)throw new Error('رابط لوحة المندوب غير مكتمل. سجّل الدخول من جديد.');const sb=await getDeliverySb(),{data:courierRows,error}=await sb.from('couriers').select('*').limit(2000);if(error)throw error;const hints=[courierHint].map(idText),data=(courierRows||[]).find(c=>[c.id,c.code,c.courier_code,c.legacy_id,c.phone].map(idText).some(v=>v&&hints.includes(v)));if(!data)throw new Error('تعذر مطابقة حساب المندوب في Supabase دون استخدام معرف UUID غير صالح.');if(data.is_active===false||data.active===false||data.disabled===true)throw new Error('حساب المندوب معطل.');const agentUuid=firstUuid(data,['delivery_agent_id','uuid','user_id','courier_uuid','id']);currentCourier={...data,_agent_uuid:agentUuid,_legacy_id:idText(data.id)};const{data:branchRows}=await sb.from('branches').select('*').limit(1000);const branchKeys=[branchHint,data.branch_id,data.branch_uuid].map(idText).filter(Boolean);currentBranch=(branchRows||[]).find(b=>[b.id,b.code,b.branch_code,b.legacy_id].map(idText).some(v=>v&&branchKeys.includes(v)))||null;currentCourier._branch_uuid=firstUuid(currentBranch,['id','uuid','branch_uuid'])||firstUuid(data,['branch_id','branch_uuid']);history.replaceState(null,'','delivery-dashboard.html?courierId='+encodeURIComponent(idText(data.id))+(data.branch_id?'&branchId='+encodeURIComponent(idText(data.branch_id)) : ''));deliveryTitle.textContent='لوحة موظف التوصيل: '+(data.name||data.phone||data.id);identityMeta.textContent='الفرع: '+(currentBranch?.name||currentBranch?.branch_name||data.branch_id||'---')+' — '+(data.phone||'')}"
s=req(s,old,new,'verify courier safely')
insert_after="function detailValue(o,key){return parseDetails(o.details)[key]||''}\n"
helpers="function courierIdentityValues(){return new Set([currentCourier?._agent_uuid,currentCourier?._legacy_id,currentCourier?.id,currentCourier?.delivery_agent_id,currentCourier?.courier_uuid].map(idText).filter(Boolean))}\nfunction orderBelongsToCourier(o){const ids=courierIdentityValues();return [o?.delivery_agent_id,o?.courier_id].map(idText).some(v=>v&&ids.has(v))}\nfunction orderBelongsToBranch(o){const expected=new Set([currentCourier?._branch_uuid,currentCourier?.branch_id,currentBranch?.id].map(idText).filter(Boolean));if(!expected.size)return true;const actual=idText(o?.branch_id);return !actual||expected.has(actual)}\nasync function fetchCourierOrders(columns='*'){const sb=await getDeliverySb(),{data,error}=await sb.from('orders').select(columns).limit(10000);if(error)throw error;return (data||[]).filter(o=>orderBelongsToCourier(o)&&orderBelongsToBranch(o))}\n"
s=req(s,insert_after,insert_after+helpers,'delivery safe order helpers')
# Replace server-side UUID filters with safe fetch+client filter functions.
start=s.index('async function loadDeliveryCounts()')
end=s.index('\nfunction renderPager()', start)
block=s[start:end]
newblock="""async function loadDeliveryCounts(){try{const rows=await fetchCourierOrders('status,details,delivery_agent_id,courier_id,branch_id');const counts={active:0,delivered:0,deferred:0,rejected:0};rows.forEach(o=>counts[tabForOrder(o)]++);Object.entries(counts).forEach(([k,v])=>{const e=document.getElementById('count-'+k);if(e)e.textContent=v})}catch(e){console.error('Delivery counts error:',e)}}
async function loadFinance(){try{const rows=(await fetchCourierOrders('status,total_price,currency,delivery_fee,delivery_payment_type,is_settled,delivery_agent_id,courier_id,branch_id')).filter(o=>o.status==='تم التسليم'),unsettled=rows.filter(o=>o.is_settled!==true),by={};unsettled.forEach(o=>{const cur=o.currency||'بدون عملة';if(!by[cur])by[cur]={collected:0,fees:0,net:0};by[cur].collected+=doorCollection(o);by[cur].fees+=Number(o.delivery_fee||0);by[cur].net+=deliveryNet(o)});cardShipments.textContent=unsettled.length;const fmt=k=>Object.entries(by).map(([c,v])=>`${v[k].toFixed(2)} ${c}`).join(' / ')||'0.00';cardCollected.textContent=fmt('collected');cardFees.textContent=fmt('fees');cardNet.textContent=fmt('net')}catch(e){console.error('Delivery finance error:',e)}}
async function loadDeliveryOrders(searchOverride=null){ordersGrid.innerHTML='<div class=\"loading\">جاري تحميل الشحنات...</div>';try{const sb=await getDeliverySb(),term=cleanSearch(searchOverride===null?deliverySearch.value:searchOverride);let q=sb.from('orders').select('*');if(term){const p='%'+term+'%';q=q.or(`order_code.ilike.${p},reference_order_no.ilike.${p},customer_name.ilike.${p},customer_phone.ilike.${p}`)}const{data,error}=await q.order('created_at',{ascending:false}).limit(10000);if(error)throw error;const scoped=(data||[]).filter(o=>orderBelongsToCourier(o)&&orderBelongsToBranch(o)),filtered=scoped.filter(o=>tabForOrder(o)===deliveryTab);deliveryTotal=filtered.length;const from=(deliveryPage-1)*deliveryPageSize;deliveryOrders=filtered.slice(from,from+deliveryPageSize);await enrichCustomers(deliveryOrders);ordersGrid.innerHTML=deliveryOrders.map(renderOrderCard).join('')||'<div class=\"empty\">لا توجد شحنات في هذا القسم.</div>';renderPager();await Promise.all([loadDeliveryCounts(),loadFinance()])}catch(error){console.error('Delivery orders error:',error);ordersGrid.innerHTML=`<div class=\"error\">${esc(error.message||error)}</div>`}}
"""
s=s[:start]+newblock+s[end:]
# Remove unsafe assignment filter on save if present.
s=s.replace(".eq('id',id).or(`delivery_agent_id.eq.${idText(currentCourier.id)},courier_id.eq.${idText(currentCourier.id)}`)", ".eq('id',id)")
s=s.replace("if(idText(row.delivery_agent_id||row.courier_id)===idText(currentCourier.id))", "if(orderBelongsToCourier(row))")
p.write_text(s,encoding='utf-8')

# employee-dashboard.html: only emit UUID delivery_agent_id.
p=Path('employee-dashboard.html'); s=p.read_text(encoding='utf-8')
marker="function cloudId(v){return v==null?'':String(v).trim()}"
s=req(s,marker,marker+"function isCloudUuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(cloudId(v))}function courierUuid(c){for(const k of ['delivery_agent_id','uuid','user_id','courier_uuid','id']){const v=cloudId(c?.[k]);if(isCloudUuid(v))return v}return''}",'employee uuid helper')
s=s.replace("const cur=cloudId(o.delivery_agent_id||o.courier_id);return '<option value=\"\">اختر موظف التوصيل</option>'+cloudCouriers.filter(c=>!o.branch_id||cloudId(c.branch_id)===cloudId(o.branch_id)).map(c=>`<option value=\"${escapeHtml(cloudId(c.id))}\" ${cloudId(c.id)===cur?'selected':''}>${escapeHtml(c.name||c.phone||c.id)}</option>`).join('')", "const cur=cloudId(o.delivery_agent_id);return '<option value=\"\">اختر موظف التوصيل</option>'+cloudCouriers.filter(c=>!o.branch_id||cloudId(c.branch_id)===cloudId(o.branch_id)).map(c=>{const u=courierUuid(c);return `<option value=\"${escapeHtml(u)}\" ${u&&u===cur?'selected':''} ${u?'':'disabled'}>${escapeHtml(c.name||c.phone||c.id)}${u?'':' — معرف غير UUID'}</option>`}).join('')")
s=s.replace("if(status==='مندوب'){if(!agentId)return alert('اختر موظف التوصيل أولاً');payload.delivery_agent_id=agentId;payload.courier_id=agentId}else if(o.status==='مندوب'){payload.delivery_agent_id=null;payload.courier_id=null}", "if(status==='مندوب'){if(!isCloudUuid(agentId))return alert('معرف موظف التوصيل غير صالح. يجب أن يكون UUID صحيحاً.');payload.delivery_agent_id=agentId}else if(o.status==='مندوب'){payload.delivery_agent_id=null}")
p.write_text(s,encoding='utf-8')

# admin-dashboard.html
p=Path('admin-dashboard.html'); s=p.read_text(encoding='utf-8')
marker="function totalPages(t,s){return Math.max(1,Math.ceil((Number(t)||0)/s))}"
s=req(s,marker,marker+"function isAdminUuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||'').trim())}function adminCourierUuid(c){for(const k of ['delivery_agent_id','uuid','user_id','courier_uuid','id']){const v=String(c?.[k]||'').trim();if(isAdminUuid(v))return v}return''}",'admin uuid helper')
s=s.replace("const cur=String(o.delivery_agent_id||o.courier_id||'');return '<option value=\"\">اختر موظف التوصيل</option>'+adminCouriersForOrders.filter(c=>!o.branch_id||String(c.branch_id)===String(o.branch_id)).map(c=>`<option value=\"${esc(c.id)}\" ${String(c.id)===cur?'selected':''}>${esc(c.name||c.phone||c.id)}</option>`).join('')", "const cur=String(o.delivery_agent_id||'');return '<option value=\"\">اختر موظف التوصيل</option>'+adminCouriersForOrders.filter(c=>!o.branch_id||String(c.branch_id)===String(o.branch_id)).map(c=>{const u=adminCourierUuid(c);return `<option value=\"${esc(u)}\" ${u&&u===cur?'selected':''} ${u?'':'disabled'}>${esc(c.name||c.phone||c.id)}${u?'':' — معرف غير UUID'}</option>`}).join('')")
s=s.replace("if(status==='مندوب'){if(!agentId)return alert('اختر موظف التوصيل أولاً');payload.delivery_agent_id=agentId;payload.courier_id=agentId}else if(o.status==='مندوب'){payload.delivery_agent_id=null;payload.courier_id=null}", "if(status==='مندوب'){if(!isAdminUuid(agentId))return alert('معرف موظف التوصيل غير صالح. يجب أن يكون UUID صحيحاً.');payload.delivery_agent_id=agentId}else if(o.status==='مندوب'){payload.delivery_agent_id=null}")
p.write_text(s,encoding='utf-8')
