import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {installMocks,openVendor,frameWindow} from './helpers.mjs';
const shared=readFileSync('js/kinto-shipping-label-v167.js','utf8');
const logo='https://labels.test/kinto.png';
const seed={id:'label-test',order_code:'KN-000101',reference_order_no:'SIP-101',created_at:'2026-10-10T12:00:00Z',customer_id:'cust',branch_id:'branch',status:'تم التسليم',delivery_payment_type:'product_paid_delivery_cod',shipping_company_name:'شركة التوصيل',details:{parcels_count:2,items:[{product_name:'محفظة جلد',quantity:1,selected_options:{color:'وردي'}},{product_name:'منتج ثانٍ',quantity:2},{product_name:'منتج ثالث',quantity:3}]} };
const customer={id:'cust',name:'عمر <script>bad</script>',code:'CUS-2675',phone:'00905378240430',secondary_phone:'07700000000',country:'العراق',state:'بغداد',address:'الكرادة، شارع الاختبار، دار 12، قرب المدرسة'};
async function prepare(page){await page.route('**/label-harness',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><body></body></html>'}));await page.goto('/label-harness');await page.addScriptTag({content:shared});await page.context().route(logo,r=>r.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a7vQAAAAASUVORK5CYII=','base64')}));await page.evaluate(({seed,customer,logo})=>{window.JsBarcode=(el,code,opts)=>{el.setAttribute('data-code',code);el.setAttribute('data-format',opts.format);};window.fixtureOrder=seed;window.fixtureCustomer=customer;window.calls=[];window.labelClient={rpc:async(name,args)=>{window.calls.push({name,args});if(name==='get_site_settings')return{data:{brand_logo_url:logo}};if(name==='vendor_shipping_label_v167')return{data:{order:{...window.fixtureOrder,items:window.fixtureOrder.details.items,customer_snapshot:window.fixtureCustomer,parcels_count:2},customer:window.fixtureCustomer,branch_name:'فرع بغداد',store_name:'متجر الاختبار'}};throw Error('unexpected rpc');},from:table=>({select:()=>({eq:()=>({maybeSingle:async()=>{window.calls.push({table});return{data:table==='orders'?window.fixtureOrder:table==='customers'?window.fixtureCustomer:{name:'فرع بغداد'}};}})})})};}, {seed,customer,logo});}
async function print(page,role='staff'){const popupPromise=page.context().waitForEvent('page');await page.evaluate(role=>{sessionStorage.setItem('meshwar_vendor_session_v95',JSON.stringify({token:'token'}));window.KintoShippingLabelV167.open({sb:window.labelClient,order:role==='vendor'?{...window.fixtureOrder,_v95SegmentId:'segment'}:window.fixtureOrder,role});},role);const popup=await popupPromise;await expect(popup.locator('#label')).toBeVisible();await expect(popup.locator('#print')).toBeEnabled();return popup;}
test('all roles share complete delivery information, 100mm square print CSS and CMS logo',async({page})=>{await prepare(page);let staff;
for(const role of ['staff','vendor']){const popup=await print(page,role);const text=await popup.locator('#label').innerText();for(const value of ['KINTO','KN-000101','SIP-101','بغداد','فرع بغداد',customer.address,customer.phone,customer.secondary_phone,'محفظة جلد','منتج ثانٍ','منتج ثالث','وردي','البضاعة مدفوعة'])expect(text).toContain(value);expect(await popup.locator('script').count()).toBe(0);await expect(popup.locator('#brand')).toHaveAttribute('data-source',logo);await expect(popup.locator('#barcode')).toHaveAttribute('data-code','KN-000101');await expect(popup.locator('#barcode')).toHaveAttribute('data-format','CODE128');expect(await popup.locator('#layout').textContent()).toContain('size:100mm 100mm');const pdf=await popup.pdf({preferCSSPageSize:true});expect(pdf.length).toBeGreaterThan(1000);expect((pdf.toString('latin1').match(/\/Type \/Page\b/g)||[]).length).toBe(1);expect(pdf.toString('latin1')).toMatch(/\/MediaBox \[0 0 28[23]\.[0-9]+ 28[23]\.[0-9]+\]/);if(role==='staff')staff=text;else expect(text.replace(' · متجر الاختبار','')).toBe(staff);await popup.close();}
expect(await page.evaluate(()=>window.fixtureOrder)).toEqual(seed);expect(await page.evaluate(()=>window.fixtureCustomer)).toEqual(customer);
for(const filename of ['vendor-dashboard-v2.html','employee-dashboard.html','admin-dashboard.html','branch-dashboard.html']){const html=readFileSync(filename,'utf8');expect(html).toContain('js/kinto-shipping-label-v167.js?v=167');expect(html).toContain('window.KintoShippingLabelV167.open');}
});
test('long multi-product orders retain every item and require larger size rather than clipping',async({page})=>{await prepare(page);await page.evaluate(()=>window.fixtureOrder.details.items=Array.from({length:30},(_,i)=>({product_name:'منتج طويل '+i,quantity:i+1})));const p=page.context().waitForEvent('page');await page.evaluate(()=>window.KintoShippingLabelV167.open({sb:window.labelClient,order:window.fixtureOrder}));const popup=await p;await expect(popup.locator('#print')).toBeDisabled();await expect(popup.locator('#message')).toContainText('زِد الارتفاع');await expect(popup.locator('#label')).toContainText('منتج طويل 29');await popup.locator('#height').fill('30');await expect(popup.locator('#print')).toBeEnabled();expect(await popup.locator('#layout').textContent()).toContain('size:100mm 300mm');});
test('fetch errors stop printing and unknown payment never becomes COD by inference',async({page})=>{await prepare(page);await page.evaluate(()=>{delete window.fixtureOrder.delivery_payment_type;});let popup=await print(page);await expect(popup.locator('#label')).toContainText('غير محددة — راجع حالة التحصيل');await popup.close();await page.evaluate(()=>window.labelClient.from=()=>({select:()=>({eq:()=>({maybeSingle:async()=>({error:{message:'forbidden'}})})})}));const p=page.context().waitForEvent('page');await page.evaluate(()=>window.KintoShippingLabelV167.open({sb:window.labelClient,order:window.fixtureOrder}));popup=await p;await expect(popup.locator('body')).toContainText('تعذر تجهيز الملصق');await expect(popup.locator('#print')).toHaveCount(0);});

test('vendor print button uses the read-only scoped RPC and leaves order/status/finance untouched',async({page})=>{
await installMocks(page);const vendor=await openVendor(page);
await frameWindow(page,async()=>{sessionStorage.setItem('meshwar_vendor_session_v95',JSON.stringify({token:'e2e-secure-token',expiresAt:new Date(Date.now()+3600000).toISOString()}));await window.loadOrders();});
await vendor.locator('#vendorTabBtn-orders').click();
const before=await frameWindow(page,()=>JSON.stringify(window.__MESH_E2E_DB));
const p=page.context().waitForEvent('page');await vendor.locator('#ordersBody tr').filter({hasText:'KN-009501'}).getByRole('button',{name:/طباعة الملصق/}).click();const popup=await p;
await expect(popup.locator('#print')).toBeEnabled();await expect(popup.locator('#label')).toContainText('بغداد');await expect(popup.locator('#label')).toContainText('الكرادة، شارع الاختبار');await expect(popup.locator('#label')).toContainText('Segment Product');
expect(await frameWindow(page,()=>JSON.stringify(window.__MESH_E2E_DB))).toBe(before);
expect(await frameWindow(page,()=>window.__MESH_E2E_RPC_CALLS.filter(x=>x.name==='vendor_shipping_label_v167').at(-1).args)).toEqual({p_session_token:'e2e-secure-token',p_segment_id:'seg-e2e-1'});
});
