const fs=require('fs'),vm=require('vm'),assert=require('assert');const root=require('path').resolve(__dirname,'..')+'/';
for(const name of ['dashboard.html','employee-dashboard.html']){const s=fs.readFileSync(root+name,'utf8');for(const m of s.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){if(m[1].trim())new vm.Script(m[1]);}}new vm.Script(fs.readFileSync(root+'js/customer-product-reviews-v135.js','utf8'));
const context={window:{},document:{addEventListener(){},createElement(){return{}},head:{appendChild(){}}},console,AbortController,setTimeout,clearTimeout,fetch:async()=>({ok:true,json:async()=>products})};vm.createContext(context);let s=fs.readFileSync(root+'js/kinto-bundle-ui-v93.js','utf8');s=s.replace('window.KintoBundleV93={','window.testRows=invoiceRows;window.KintoBundleV93={');vm.runInContext(s,context);const api=context.window.KintoBundleV93,id='b124f9f1-b124-4a79-bba1-a33a9e0170d3';let products=[];let tests=0;
const line=(color,q=2,extra={})=>({product_id:id,product_name:'منتج',quantity:q,selected_options:{color,...extra},unit_price_local:8000,line_total_local:q*8000});const order=(lines,status='تمت الموافقة - بانتظار الدفع')=>({status,details:{source:'local_cart_bundle',items:lines}});const product=(total=10,color={أبيض:5,أزرق:5},matrix={})=>({id,stock_quantity:total,options:{variant_stock:{color},matrix_stock:matrix}});function check(fn){fn();tests++}
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',5)]),[product()]).length,0));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',6)]),[product()])[0].issues[0].available,5));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',3),line('أبيض',3)]),[product()]).length,2));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',5),line('أزرق',5)]),[product()]).length,0));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',5),line('أزرق',5)]),[product(8)])[0].issues[0].requested,10));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',2)],'تم التسديد'),[product(0)]).length,0));
check(()=>{const o=order([line('أبيض')]);o.details.bundle_stock_lifecycle_state='deducted';assert.equal(api.stockWarnings(o,[product(0)]).length,0)});
check(()=>assert.equal(api.stockWarnings(order([line('أبيض')]),[product(null,{أبيض:0})]).length,0));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض')]),[product(10,{أبيض:null})]).length,0));
check(()=>assert.equal(api.stockWarnings(order([line('أبيض',2,{size:'L'})]),[product(10,{أبيض:5},{'أبيض_L':1})])[0].issues[0].kind,'matrix'));
check(()=>{const p=product();p.options.variant_stock.material={جلد:1};assert.equal(api.stockWarnings(order([line('أبيض',2,{material:'جلد'})]),[p])[0].issues[0].label,'جلد')});
check(()=>assert.equal(api.stockWarnings(order([{...line(''),color:'أبيض'}]),[product(10,{أبيض:0})])[0].issues[0].available,0));
check(()=>{const o=order([line('أبيض',6),line('أزرق',1)]),w=api.stockWarnings(o,[product()]),html=context.window.testRows({items:o.details.items,currency:'IQD'},w);assert.equal((html.match(/stock-shortage-row/g)||[]).length,1);assert(html.includes('48,000'));assert(html.includes('المتاح 5'))});
(async()=>{products=[product(10,{أبيض:0})];const o=order([line('أبيض')]);const original=JSON.stringify(o.details);await api.refreshStockWarnings([o]);assert.equal(o._stockShortagesV53.length,1);tests++;products=[product()];await api.refreshStockWarnings([o]);assert.equal(o._stockShortagesV53.length,0);assert.equal(JSON.stringify(o.details),original);tests++;context.fetch=async()=>{throw Error('offline')};await assert.rejects(()=>api.refreshStockWarnings([o]));assert(o._stockCheckErrorV53);assert(!o._stockShortagesV53);tests++;
const emp=fs.readFileSync(root+'employee-dashboard.html','utf8');let updates=0;const ec={window:{KintoBundleV93:api},updateEmployeeStockIconsV53(){},console};vm.createContext(ec);vm.runInContext(emp.match(/async function checkEmployeePaymentStockV53\(o\)\{[^\n]+/)[0],ec);context.fetch=async()=>({ok:true,json:async()=>[product(0)]});await assert.rejects(()=>ec.checkEmployeePaymentStockV53(order([line('أبيض')])).then(()=>updates++));assert.equal(updates,0);tests++;assert(emp.indexOf("await checkEmployeePaymentStockV53(o)")<emp.indexOf("await sb.from('orders').update(payload)"));tests++;console.log(tests+' shortage tests passed; all modified inline scripts parse');})().catch(e=>{console.error(e);process.exit(1)});
