from pathlib import Path
p=Path('dashboard.html')
s=p.read_text(encoding='utf-8')

# Invoice modal styling.
needle='.modal-content{background:white;padding:22px;border-radius:16px;width:min(92%,540px);max-height:86vh;overflow:auto;box-shadow:0 16px 50px rgba(0,0,0,.22)}'
extra=needle+'''.invoice-modal{width:min(94%,720px);padding:0;overflow:hidden}.invoice-sheet{background:#fff}.invoice-head{padding:20px 22px;background:#07111f;color:#fff;display:flex;justify-content:space-between;align-items:center;gap:14px}.invoice-head h3{margin:0;font-size:21px}.invoice-body{padding:20px 22px}.invoice-product{display:flex;gap:14px;align-items:center;padding-bottom:16px;border-bottom:1px solid #e5e7eb}.invoice-product img{width:78px;height:78px;object-fit:cover;border-radius:12px;border:1px solid #e5e7eb}.invoice-lines{margin-top:16px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden}.invoice-line{display:flex;justify-content:space-between;gap:15px;padding:11px 13px;border-bottom:1px solid #eef2f7}.invoice-line:last-child{border-bottom:0}.invoice-total{font-size:18px;font-weight:900;background:#f8fafc}.invoice-warning{margin-top:16px;padding:14px;border:1px solid #f59e0b;background:#fffbeb;color:#92400e;border-radius:12px;line-height:1.8;font-weight:700}.invoice-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.invoice-print{background:#07111f;color:#fff;border:0;border-radius:9px;padding:9px 13px;font-weight:800;cursor:pointer}.invoice-close{background:#e2e8f0;color:#334155;border:0;border-radius:9px;padding:9px 13px;font-weight:800;cursor:pointer}@media print{body>*{display:none!important}#customerApprovalInvoiceModal{display:block!important;position:static!important;background:#fff!important;padding:0!important}#customerApprovalInvoiceModal .modal-content{display:block!important;width:100%!important;max-height:none!important;box-shadow:none!important}.invoice-actions{display:none!important}}'''
assert needle in s
s=s.replace(needle,extra,1)

# Dedicated approval invoice modal.
needle='<div id="customerOrderDetailsModal" class="modal-overlay"><div class="modal-content"><h3>تفاصيل الطلب</h3><div id="customerOrderDetailsContent"></div><button onclick="closeCustomerOrderDetails()" class="btn-action">إغلاق</button></div></div>'
extra=needle+'\n<div id="customerApprovalInvoiceModal" class="modal-overlay"><div class="modal-content invoice-modal"><div id="customerApprovalInvoiceContent"></div></div></div>'
assert needle in s
s=s.replace(needle,extra,1)

# Approval/approved row controls open the invoice rather than directly mutating status.
start=s.index('function customerDecisionHtml(order,index,price,currency){')
end=s.index('\nfunction getOrderSiparisNo',start)
new_dec='''function customerDecisionHtml(order,index,price,currency){const status=String(order.status||'انتظار رد الموظف').trim(),priced=price!==null&&Number.isFinite(price)&&price>0,editable=canCustomerEditStatus(status);if(isWaitingCustomerApprovalStatus(status)&&priced)return `<div class="decision-box"><button class="btn-approve" onclick="openCustomerApprovalInvoice(${index})">عرض الفاتورة والموافقة</button><button class="btn-cancel" onclick="cancelOrder(${index})">إلغاء</button></div>`;if(status==='تمت الموافقة - بانتظار الدفع'||status==='تمت الموافقة'||status==='approved')return `<div class="decision-box"><span style="font-weight:800;color:#16865b">✓ تمت الموافقة</span><button class="btn-details" onclick="openCustomerApprovalInvoice(${index})">عرض الفاتورة</button>${editable?`<button class="btn-cancel" onclick="cancelOrder(${index})">إلغاء</button>`:''}</div>`;if(!editable)return '---';return `<div class="decision-box"><button class="btn-cancel" onclick="cancelOrder(${index})">إلغاء</button></div>`;}'''
s=s[:start]+new_dec+s[end:]

# Replace old direct approval with invoice workflow. Backend RPC atomically approves and preserves delivery_fee.
start=s.index('async function approveOrder(i){')
end=s.index('\nasync function editCustomerOrder',start)
new_flow=r'''function invoiceStatusApproved(status){return ['approved','تمت الموافقة','تمت الموافقة - بانتظار الدفع'].includes(String(status||'').trim())}
function closeCustomerApprovalInvoice(){document.getElementById('customerApprovalInvoiceModal').style.display='none'}
function renderCustomerApprovalInvoice(i,order){const o=order||currentCustomerOrdersGlobal[i];if(!o)return;const money=customerOrderMoneyBreakdown(o),currency=escapeHtml(o.currency||'$'),qty=o._quantity||getOrderQuantity(o),parcels=getOrderParcelsCount(o),siparis=getOrderSiparisNo(o),approved=invoiceStatusApproved(o.status),deliveryAdded=Number(o.delivery_fee)>0,image=o.image_url?`<img src="${escapeHtml(o.image_url)}" alt="صورة المنتج" onerror="this.style.display='none'">`:'';const product=money.productTotal===null?'---':money.productTotal.toFixed(2)+' '+currency,external=money.externalShippingFee.toFixed(2)+' '+currency,delivery=deliveryAdded?money.deliveryFee.toFixed(2)+' '+currency:'(سيضاف عند وصول المنتج للفرع)',grand=money.grandTotal===null?'---':money.grandTotal.toFixed(2)+' '+currency;const warning=!deliveryAdded?`<div class="invoice-warning">⚠️ تنبيه هام: السعر الحالي الذي توافق عليه يشمل سعر السلعة والشحن الخارجي فقط، <strong>ولا يشمل أجور التوصيل المحلي</strong> (والتي ستحتسب وتضاف لاحقاً عند وصول الطلب لفرع التوصيل المحلي). بالموافقة أنت تقر وتوافق على هذا الشرط.</div>`:'';document.getElementById('customerApprovalInvoiceContent').innerHTML=`<div class="invoice-sheet"><div class="invoice-head"><h3>فاتورة الطلب الرسمية</h3><b>${escapeHtml(o.order_code||o.id)}</b></div><div class="invoice-body"><div class="invoice-product">${image}<div><b>${escapeHtml(o.order_code||'طلب')}</b><div>Sipariş No: ${escapeHtml(siparis||'---')}</div><div>الكمية: ${escapeHtml(qty)} &nbsp; • &nbsp; الطرود: ${escapeHtml(parcels)}</div></div></div><div class="invoice-lines"><div class="invoice-line"><span>سعر السلعة</span><b>${product}</b></div><div class="invoice-line"><span>أجور الشحن الخارجي</span><b>${external}</b></div><div class="invoice-line"><span>أجرة التوصيل المحلي</span><b>${delivery}</b></div><div class="invoice-line invoice-total"><span>المجموع الكلي النهائي الحالي</span><b>${grand}</b></div></div>${warning}<div class="invoice-actions">${approved?`<button class="invoice-print" onclick="printApprovedCustomerInvoice(${i})">طباعة / حفظ PDF</button>`:`<button class="btn-approve" onclick="confirmCustomerInvoiceApproval(${i})">تأكيد وموافقة نهائية</button><button class="btn-cancel" onclick="cancelOrderFromInvoice(${i})">إلغاء / تراجع</button>`}<button class="invoice-close" onclick="closeCustomerApprovalInvoice()">إغلاق</button></div></div></div>`;document.getElementById('customerApprovalInvoiceModal').style.display='flex'}
function openCustomerApprovalInvoice(i){const o=currentCustomerOrdersGlobal[i];if(!o)return;if(['ملغي من قبل العميل','رفض الطلب','مرفوض'].includes(String(o.status||'')))return alert('لا يمكن فتح أو طباعة فاتورة طلب ملغي أو مرفوض.');renderCustomerApprovalInvoice(i,o)}
async function confirmCustomerInvoiceApproval(i){const o=currentCustomerOrdersGlobal[i];if(!o||!isWaitingCustomerApprovalStatus(o.status)||!(Number(o.total_price)>0))return alert('هذا الطلب غير متاح للموافقة حالياً.');try{const sb=await ensureCustomerPortalSupabase(),{data,error}=await sb.rpc('customer_approve_order_invoice',{p_order_id:String(o.id),p_customer_id:String(currentCustomerCloud.id)});if(error)throw error;await loadCustomerOrdersFromCloud(currentCustomerCloud.id);const idx=currentCustomerOrdersGlobal.findIndex(x=>String(x.id)===String(o.id));if(idx>=0)renderCustomerApprovalInvoice(idx,currentCustomerOrdersGlobal[idx]);else closeCustomerApprovalInvoice()}catch(e){console.error('Approve invoice error:',e);alert('تعذر تأكيد الموافقة: '+(e.message||e))}}
async function approveOrder(i){return openCustomerApprovalInvoice(i)}
async function cancelOrderFromInvoice(i){closeCustomerApprovalInvoice();await cancelOrder(i)}
async function printApprovedCustomerInvoice(i){const o=currentCustomerOrdersGlobal[i];if(!o||!invoiceStatusApproved(o.status))return alert('لا يمكن طباعة الفاتورة قبل الموافقة النهائية.');try{const sb=await ensureCustomerPortalSupabase(),{data,error}=await sb.rpc('customer_get_approved_invoice',{p_order_id:String(o.id),p_customer_id:String(currentCustomerCloud.id)});if(error)throw error;if(!data||!invoiceStatusApproved(data.status))throw new Error('INVOICE_EXPORT_NOT_ALLOWED');const latest={...o,...data};renderCustomerApprovalInvoice(i,latest);setTimeout(()=>window.print(),80)}catch(e){console.error('Invoice export blocked:',e);alert('تم منع طباعة الفاتورة: يجب أن يكون الطلب موافقاً عليه وغير ملغي.')}}'''
s=s[:start]+new_flow+s[end:]

# Export modal handlers to inline buttons.
old='Object.assign(window,{switchCustomerTab,openRewardsModal,closeRewardsModal,openCustomerOrderDetails,closeCustomerOrderDetails,approveOrder,cancelOrder,saveAddress,saveSecondaryPhone,sendCustomerMessage,copyWarehouseAddress,saveCloudDraft,deleteCloudDraft,handleCustomerChatFile,refreshCustomerUnreadCount,markCustomerMessagesRead});'
new='Object.assign(window,{switchCustomerTab,openRewardsModal,closeRewardsModal,openCustomerOrderDetails,closeCustomerOrderDetails,approveOrder,cancelOrder,openCustomerApprovalInvoice,closeCustomerApprovalInvoice,confirmCustomerInvoiceApproval,cancelOrderFromInvoice,printApprovedCustomerInvoice,saveAddress,saveSecondaryPhone,sendCustomerMessage,copyWarehouseAddress,saveCloudDraft,deleteCloudDraft,handleCustomerChatFile,refreshCustomerUnreadCount,markCustomerMessagesRead});'
assert old in s
s=s.replace(old,new,1)

p.write_text(s,encoding='utf-8')
