from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old_nav='''<nav class="sticky top-0 z-50 border-b border-white/10 bg-slate-950/90 shadow-lg shadow-black/20 backdrop-blur-xl dark:bg-slate-950/90"><div class="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3"><a href="index.html" class="flex items-center gap-2 font-black text-slate-900 no-underline dark:text-white"><img src="images/meshwar-logo.png" class="h-12 w-12 rounded-xl border border-amber-400/40 bg-white/5 p-1 shadow-lg shadow-amber-400/10" alt="KINTO"></a><div class="flex items-center gap-2"><a href="#localStoresPublic" class="rounded-full border border-white/10 px-3 py-2 text-xs font-bold text-slate-700 no-underline dark:text-slate-200">🏪 المتاجر</a><button id="meshwarThemeToggle" type="button" class="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-slate-700 dark:text-slate-100">☾</button></div></div></nav>'''
new_nav='''<nav class="sticky top-0 z-50 border-b border-white/10 bg-slate-950/90 shadow-lg shadow-black/20 backdrop-blur-xl dark:bg-slate-950/90"><div class="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3"><a href="index.html" class="flex items-center gap-2 font-black text-slate-900 no-underline dark:text-white"><img src="images/meshwar-logo.png" class="h-12 w-12 rounded-xl border border-amber-400/40 bg-white/5 p-1 shadow-lg shadow-amber-400/10" alt="KINTO"></a><div class="flex flex-wrap items-center justify-end gap-2"><a href="#localStoresPublic" class="rounded-full border border-white/10 px-3 py-2 text-xs font-bold text-slate-700 no-underline dark:text-slate-200">🏪 المتاجر</a><button id="meshwarThemeToggle" type="button" class="rounded-full border border-white/10 bg-white/5 px-3 py-2 text-slate-700 dark:text-slate-100">☾</button><div class="user-auth-zone" style="text-align:center"><a href="#" id="authLink" class="account-btn"><i class="fa-solid fa-circle-user"></i><span id="authText">حسابي / تسجيل</span></a><a href="#" id="logoutBtn" onclick="logout()" class="header-logout-btn" style="display:none">تسجيل خروج</a></div></div></div></nav>'''
assert old_nav in s, 'top nav block not found'
s=s.replace(old_nav,new_nav,1)
old_float='''    <div class="user-auth-zone" style="text-align: center;"><a href="#" id="authLink" class="account-btn"><i class="fa-solid fa-circle-user"></i> <span id="authText">حسابي / تسجيل</span></a><br><a href="#" id="logoutBtn" onclick="logout()" style="display:none; color: #cc0000; font-size: 13px; margin-top: 8px; text-decoration: none; font-weight: bold;">تسجيل خروج</a></div>\n'''
assert old_float in s, 'floating auth block not found'
s=s.replace(old_float,'',1)
s=s.replace('.user-auth-zone{@apply !fixed !bottom-4 !left-4 !top-auto;}','.user-auth-zone{@apply !static flex items-center gap-2;}')
css='''\n<style id="indexAuthHeaderV51">\n.user-auth-zone{position:static!important;display:flex!important;align-items:center!important;gap:8px!important;z-index:auto!important}.user-auth-zone .account-btn{padding:8px 13px!important;border-radius:999px!important;font-size:12px!important;line-height:1!important;box-shadow:none!important;white-space:nowrap}.header-logout-btn{display:inline-flex;align-items:center;justify-content:center;padding:8px 12px;border-radius:999px;border:1px solid rgba(248,113,113,.35);background:rgba(127,29,29,.18);color:#fecaca!important;text-decoration:none!important;font-size:12px;font-weight:900;white-space:nowrap}.header-logout-btn:hover{background:rgba(185,28,28,.28);border-color:rgba(248,113,113,.6)}@media(max-width:640px){.user-auth-zone{gap:5px!important}.user-auth-zone .account-btn,.header-logout-btn{padding:7px 9px!important;font-size:11px!important}}\n</style>\n'''
s=s.replace('</head>',css+'</head>',1)
assert s.count('id="authLink"')==1
assert s.count('id="logoutBtn"')==1
assert '!fixed !bottom-4 !left-4 !top-auto' not in s
p.write_text(s,encoding='utf-8')
