const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('js/kinto-unified-shipping-label-v1.js','utf8');
const window={open(){throw Error('Not called')}};
vm.runInNewContext(source,{window});
const render=window.KintoUnifiedShippingLabel.render;
const base={orderCode:'KN-000065',customerName:'Test',governorate:'بغداد',pieces:6,parcels:1};
const missing=render(base);
assert.match(missing,/يلزم التحقق من المبالغ/);
assert.doesNotMatch(missing,/100,000/);
const paid=render({...base,verifiedOutstanding:{verified:true,products:0,externalShipping:0,internalDelivery:0,currency:'IQD'}});
assert.match(paid,/مدفوع بالكامل/);
const due=render({...base,verifiedOutstanding:{verified:true,products:0,externalShipping:10000,internalDelivery:5000,currency:'IQD'}});
assert.match(due,/15,000 IQD/);
assert.doesNotMatch(due,/المتبقي — المنتجات/);
assert.match(due,/المحافظة/);
assert.doesNotMatch(due,/MeshWar Cargo/);
const invalid=render({...base,verifiedOutstanding:{verified:true,products:0,externalShipping:null,internalDelivery:5000}});
assert.match(invalid,/يلزم التحقق من المبالغ/);
assert.doesNotMatch(invalid,/5,000 IQD/);
console.log('KINTO label renderer contract tests passed');
