const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const window={};vm.runInNewContext(fs.readFileSync('js/kinto-unified-shipping-label-v1.js','utf8'),{window});
const render=window.KintoUnifiedShippingLabel.render;
const base={orderCode:'KN-000065',governorate:'بغداد',pieces:6,parcels:1};
const item=(status,amount)=>({status,amount,currency:'IQD'});
assert.match(render(base),/يلزم التحقق/);
const paid=render({...base,collectionCharges:{products:item('collected',100000),externalShipping:item('collected',15000),internalDelivery:item('collected',5000)}});
assert.match(paid,/لا توجد مبالغ للتحصيل/);assert.doesNotMatch(paid,/100,000|15,000|5,000/);
const due=render({...base,collectionCharges:{products:item('collected',100000),externalShipping:item('uncollected',15000),internalDelivery:item('uncollected',5000)}});
assert.match(due,/15,000 IQD/);assert.match(due,/5,000 IQD/);assert.doesNotMatch(due,/100,000/);
const unknown=render({...base,collectionCharges:{products:item('collected',100000),externalShipping:item('unknown',15000),internalDelivery:item('collected',5000)}});
assert.match(unknown,/توجد بنود لم يتم التحقق/);assert.doesNotMatch(unknown,/15,000 IQD/);
assert.doesNotMatch(due,/MeshWar Cargo/);
console.log('Binary collection label tests passed');
