import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const sql=readFileSync('supabase/migrations/20261004_kinto_deals_v1_g7_public_display_off.sql','utf8');
const js=readFileSync('js/kinto-deals-customer-g7.js','utf8');
const local=readFileSync('local-stores.html','utf8');
const store=readFileSync('store.html','utf8');
assert.match(sql,/merchant_deals_public_display_g7',false/);
assert.match(sql,/published boolean not null default false/);
assert.match(sql,/pub\.published=true/);
assert.match(sql,/latest\.review_state='acknowledged'/);
assert.match(sql,/e\.decision='approved'/);
assert.match(sql,/c\.starts_at<=statement_timestamp\(\)/);
assert.match(sql,/c\.ends_at>statement_timestamp\(\)/);
assert.match(sql,/revoke all on public\.kinto_deals_v1_publications_g7 from public,anon,authenticated/);
assert.doesNotMatch(sql,/update\s+public\.orders|alter\s+table\s+public\.orders|merchant_deals_enabled',true/i);
assert.match(js,/kinto_deals_v1_public_feed_g7/);
assert.match(js,/\.kd-g7-badge/);
assert.match(js,/kintoMerchantDealsG7/);
assert.doesNotMatch(js,/active_kinto_campaigns_v400|local_cart|checkout|insert\s+into/i);
assert.match(local,/js\/kinto-deals-customer-g7\.js/);
assert.match(store,/js\/kinto-deals-customer-g7\.js/);
console.log('G7 isolation and fail-closed static checks passed');
