import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const js=readFileSync(new URL('../js/customer-product-reviews-v135.js',import.meta.url),'utf8');
const admin=readFileSync(new URL('../js/admin-product-reviews-v138.js',import.meta.url),'utf8');
const store=readFileSync(new URL('../js/store-product-reviews-v140.js',import.meta.url),'utf8');
const sql=readFileSync(new URL('../supabase/migrations/20260912_v150_review_images_storage_tickets.sql',import.meta.url),'utf8');
assert.match(js,/COMPRESSED_TARGET_BYTES = 25 \* 1024/);
assert.match(js,/COMPRESSED_MAX_BYTES = 50 \* 1024/);
assert.match(js,/COMPRESSED_MAX_DIMENSION = 320/);
assert.match(js,/customer_create_review_image_upload_v150/);
assert.match(js,/customer_finalize_review_image_upload_v150/);
assert.match(js,/\.storage\.from\(bucket\)\.upload/);
assert.doesNotMatch(js,/p_base64|btoa\(binary\)/);
assert.match(sql,/product_review_upload_tickets_v150/);
assert.match(sql,/review_storage_upload_allowed_v150/);
assert.match(sql,/file_size_limit = 51200/);
assert.match(sql,/left join public\.product_review_image_payloads/);
assert.match(sql,/storage_path like 'database:\/\/%'/);
assert.match(sql,/deleted_storage_paths/);
assert.match(admin,/data\?\.storage_path/);
assert.match(store,/reviewImageUrl/);
assert.doesNotMatch(sql,/(update|insert into|delete from) public\.(orders|customers|employees|invoices|local_products)/i);
console.log('Review image V150 secure Storage ticket contract: OK');
