from pathlib import Path

p = Path('vendor-dashboard.html')
s = p.read_text(encoding='utf-8')
old = """async function loadOrders(){if(!vendorStore)return;try{const{data,error}=await sb.from('orders').select('id,order_code,total_price,currency,status,created_at,details').contains('details',{source:'local_store',store_id:String(vendorStore.id)}).order('created_at',{ascending:false}).limit(200);if(error)throw error;orders=data||[];$('ordersBody').innerHTML=orders.map(o=>`<tr class=\"border-b border-white/5\"><td class=\"p-3\"><div class=\"font-bold\">${esc(o.order_code||String(o.id).slice(0,8))}</div><div class=\"vendor-muted text-xs text-slate-500\">${new Date(o.created_at).toLocaleString('ar')}</div></td><td>${esc(orderProductName(o))}</td><td>${orderQuantity(o)}</td><td>${esc(orderCity(o))}</td><td><span class=\"rounded-full border border-white/10 bg-white/5 px-2 py-1 text-xs\">${esc(o.status||'انتظار رد الموظف')}</span></td><td><button type=\"button\" onclick=\"printShippingLabel('${esc(o.id)}')\" class=\"rounded-lg border border-sky-400/30 bg-sky-500/10 px-3 py-2 text-xs font-black text-sky-200 transition hover:bg-sky-500/20\">🖨️ طباعة الملصق</button></td></tr>`).join('')||'<tr><td colspan=\"6\" class=\"p-6 text-center text-slate-400\">لا توجد طلبات واردة لهذا المتجر.</td></tr>';renderFinance();renderStats()}catch(e){console.error('Vendor orders load error:',e);showNotice('تعذر تحميل الطلبات: '+(e.message||e),true)}}"""
new = """async function loadOrders(){if(!vendorStore)return;try{const currentStoreId=String(vendorStore.id||'').trim();if(!currentStoreId)throw new Error('معرّف المتجر الحالي غير صالح.');const{data,error}=await sb.from('orders').select('id,order_code,total_price,currency,status,created_at,details').order('created_at',{ascending:false}).limit(500);if(error)throw error;orders=(data||[]).filter(o=>{const d=normalizeOrderDetails(o?.details);return String(d?.source||'')==='local_store'&&String(d?.store_id||'').trim()===currentStoreId});$('ordersBody').innerHTML=orders.map(o=>`<tr class=\"border-b border-white/5\"><td class=\"p-3\"><div class=\"font-bold\">${esc(o.order_code||String(o.id).slice(0,8))}</div><div class=\"vendor-muted text-xs text-slate-500\">${new Date(o.created_at).toLocaleString('ar')}</div></td><td>${esc(orderProductName(o))}</td><td>${orderQuantity(o)}</td><td>${esc(orderCity(o))}</td><td><span class=\"rounded-full border border-white/10 bg-white/5 px-2 py-1 text-xs\">${esc(o.status||'انتظار رد الموظف')}</span></td><td><button type=\"button\" onclick=\"printShippingLabel('${esc(o.id)}')\" class=\"rounded-lg border border-sky-400/30 bg-sky-500/10 px-3 py-2 text-xs font-black text-sky-200 transition hover:bg-sky-500/20\">🖨️ طباعة الملصق</button></td></tr>`).join('')||'<tr><td colspan=\"6\" class=\"p-6 text-center text-slate-400\">لا توجد طلبات واردة لهذا المتجر.</td></tr>';renderFinance();renderStats()}catch(e){console.error('Vendor orders load error:',e);showNotice('تعذر تحميل الطلبات: '+(e.message||e),true)}}"""
if old not in s:
    raise SystemExit('target loadOrders block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
