from pathlib import Path
p=Path('vendor-dashboard.html')
s=p.read_text(encoding='utf-8')
old="""*{box-sizing:border-box}html,body{width:50mm;height:40mm;margin:0;padding:1.5mm;font-family:Arial,sans-serif;color:#000;background:#fff;font-size:8px;overflow:hidden}.label-card{width:100%;height:100%;box-sizing:border-box;border:1px solid #000;padding:2px;display:flex;flex-direction:column;justify-content:space-between;gap:1px;overflow:hidden}.brand{text-align:center;border-bottom:1px solid #000;padding-bottom:1px;line-height:1}.brand h1{margin:0;font-size:9px;font-weight:900}.brand p{margin:0;font-size:6.5px}.order{text-align:center;font-size:9px;font-weight:900;line-height:1;direction:ltr}.barcode{height:22px;min-height:22px;display:flex;align-items:center;justify-content:center;overflow:hidden}.barcode svg{width:100%;max-width:100%;height:22px}.grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid #000;line-height:1.05}.cell{padding:1px;border:1px solid #cbd5e1;min-width:0}.label-title{font-size:6.5px;color:#475569;margin-bottom:0}.value{font-size:7.5px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product{grid-column:1/-1}@media print{@page{size:50mm 40mm;margin:0}html,body{width:50mm!important;height:40mm!important;margin:0!important;padding:1.5mm!important;box-sizing:border-box;font-size:8px;overflow:hidden;page-break-after:avoid!important}.label-card{width:100%;height:100%;max-height:37mm;box-sizing:border-box;border:1px solid #000;padding:2px;display:flex;flex-direction:column;justify-content:space-between;page-break-inside:avoid!important;page-break-after:avoid!important;break-inside:avoid!important;break-after:avoid!important;overflow:hidden}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}"""
new="""*{box-sizing:border-box}html,body{width:50mm;height:40mm;margin:0;padding:0;font-family:Arial,sans-serif;color:#000;background:#fff;font-size:8px;overflow:hidden}.label-card{position:absolute;inset:.8mm;width:auto;height:auto;max-height:38.4mm;box-sizing:border-box;border:1px solid #000;padding:1.5px;display:flex;flex-direction:column;justify-content:space-between;gap:.5px;overflow:hidden}.brand{text-align:center;border-bottom:1px solid #000;padding-bottom:.5px;line-height:1}.brand h1{margin:0;font-size:9px;font-weight:900}.brand p{margin:0;font-size:6.5px}.order{text-align:center;font-size:9px;font-weight:900;line-height:1;direction:ltr}.barcode{height:22px;min-height:22px;display:flex;align-items:center;justify-content:center;overflow:hidden}.barcode svg{width:100%;max-width:100%;height:22px}.grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid #000;line-height:1.02}.cell{padding:.75px;border:1px solid #cbd5e1;min-width:0}.label-title{font-size:6.5px;color:#475569;margin-bottom:0}.value{font-size:7.5px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.product{grid-column:1/-1}@media print{@page{size:50mm 40mm;margin:0}html,body{width:50mm!important;height:40mm!important;min-height:40mm!important;max-height:40mm!important;margin:0!important;padding:0!important;box-sizing:border-box!important;overflow:hidden!important}.label-card{position:fixed!important;inset:.8mm!important;width:auto!important;height:auto!important;max-height:38.4mm!important;box-sizing:border-box!important;border:1px solid #000;padding:1.5px!important;display:flex!important;flex-direction:column!important;justify-content:space-between!important;gap:.5px!important;page-break-inside:avoid!important;page-break-before:avoid!important;page-break-after:avoid!important;break-inside:avoid!important;break-before:avoid!important;break-after:avoid!important;overflow:hidden!important}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}"""
if old not in s: raise SystemExit('vendor label style anchor not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('vendor one-sheet label patch applied')
