-- KINTO V141: anonymous helpful votes and published review projection.
-- Isolated from orders, tracking, employees, invoices, and cart logic.

begin;

create table if not exists public.product_review_helpful_votes (
  id bigint generated by default as identity primary key,
  review_id uuid not null references public.product_reviews(id) on update cascade on delete cascade,
  visitor_hash bytea not null,
  created_at timestamptz not null default now(),
  constraint product_review_helpful_votes_unique unique(review_id, visitor_hash)
);

create index if not exists idx_product_review_helpful_votes_review
  on public.product_review_helpful_votes(review_id);

alter table public.product_review_helpful_votes enable row level security;
revoke all on public.product_review_helpful_votes from public, anon, authenticated;

create or replace function public.product_review_helpful_toggle_v141(
  p_review_id uuid,
  p_visitor_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_hash bytea;
  v_liked boolean;
  v_count integer;
begin
  if p_visitor_token is null or char_length(p_visitor_token) not between 20 and 200 then
    raise exception 'INVALID_VISITOR_TOKEN';
  end if;
  if not exists (
    select 1 from public.product_reviews r
    where r.id = p_review_id and r.moderation_status = 'published'
  ) then raise exception 'PUBLISHED_REVIEW_NOT_FOUND'; end if;

  v_hash := digest(p_visitor_token, 'sha256');
  perform pg_advisory_xact_lock(hashtextextended(p_review_id::text || encode(v_hash,'hex'), 141));
  if exists (select 1 from public.product_review_helpful_votes where review_id=p_review_id and visitor_hash=v_hash) then
    delete from public.product_review_helpful_votes where review_id=p_review_id and visitor_hash=v_hash;
    v_liked := false;
  else
    insert into public.product_review_helpful_votes(review_id, visitor_hash) values(p_review_id, v_hash);
    v_liked := true;
  end if;
  select count(*)::integer into v_count from public.product_review_helpful_votes where review_id=p_review_id;
  return jsonb_build_object('review_id',p_review_id,'liked',v_liked,'helpful_count',v_count);
end;
$$;

revoke all on function public.product_review_helpful_toggle_v141(uuid,text) from public;
grant execute on function public.product_review_helpful_toggle_v141(uuid,text) to anon, authenticated;

create or replace function public.product_reviews_public_v141(
  p_product_id uuid,
  p_visitor_token text default null,
  p_limit integer default 8,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
stable
set search_path = public, extensions, pg_temp
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit,8),1),20);
  v_offset integer := greatest(coalesce(p_offset,0),0);
  v_hash bytea := case when char_length(coalesce(p_visitor_token,'')) between 20 and 200 then digest(p_visitor_token,'sha256') else null end;
  v_count bigint;
  v_average numeric;
  v_items jsonb;
begin
  select count(*),round(avg(r.rating)::numeric,1) into v_count,v_average
  from public.product_reviews r where r.product_id=p_product_id and r.moderation_status='published';

  select coalesce(jsonb_agg(to_jsonb(q) order by q.created_at desc),'[]'::jsonb) into v_items
  from (
    select r.id,
      case when nullif(trim(coalesce(c.name,'')),'') is null then 'عميل KINTO' else left(trim(c.name),1)||'***' end as customer_name,
      r.rating,r.comment,r.verified_purchase,r.created_at,
      (select count(*)::integer from public.product_review_helpful_votes h where h.review_id=r.id) as helpful_count,
      exists(select 1 from public.product_review_helpful_votes h where h.review_id=r.id and h.visitor_hash=v_hash) as liked,
      coalesce((select jsonb_agg(jsonb_build_object(
        'id',i.id,'mime_type',i.mime_type,
        'data_url','data:'||i.mime_type||';base64,'||encode(p.image_bytes,'base64'),
        'sort_order',i.sort_order
      ) order by i.sort_order)
      from public.product_review_images i join public.product_review_image_payloads p on p.image_id=i.id
      where i.review_id=r.id and i.moderation_status='published'),'[]'::jsonb) as images
    from public.product_reviews r left join public.customers c on c.id=r.customer_id
    where r.product_id=p_product_id and r.moderation_status='published'
    order by r.created_at desc limit v_limit offset v_offset
  ) q;
  return jsonb_build_object('product_id',p_product_id,'count',coalesce(v_count,0),'average_rating',coalesce(v_average,0),'items',v_items,'limit',v_limit,'offset',v_offset);
end;
$$;

revoke all on function public.product_reviews_public_v141(uuid,text,integer,integer) from public;
grant execute on function public.product_reviews_public_v141(uuid,text,integer,integer) to anon, authenticated;

commit;
