-- KINTO V149: additive verified courier sessions.
-- Does not alter couriers, branches, employees, orders, invoices, messages, customers, or existing functions.

begin;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;

create table if not exists public.courier_sessions_v149 (
  id uuid primary key default gen_random_uuid(),
  courier_id text not null,
  token_hash bytea not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists courier_sessions_v149_actor_active_idx
  on public.courier_sessions_v149(courier_id, expires_at desc)
  where revoked_at is null;

alter table public.courier_sessions_v149 enable row level security;
revoke all on table public.courier_sessions_v149 from public, anon, authenticated;

create table if not exists public.courier_login_attempts_v149 (
  id bigint generated by default as identity primary key,
  identity_hash bytea not null,
  attempted_at timestamptz not null default now()
);

create index if not exists courier_login_attempts_v149_identity_time_idx
  on public.courier_login_attempts_v149(identity_hash, attempted_at desc);

alter table public.courier_login_attempts_v149 enable row level security;
revoke all on table public.courier_login_attempts_v149 from public, anon, authenticated;

create or replace function private.require_courier_session_v149(p_session_token text)
returns text
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_courier_id text;
begin
  if trim(coalesce(p_session_token, '')) = '' then
    raise exception 'COURIER_SESSION_REQUIRED';
  end if;

  select s.courier_id into v_courier_id
  from public.courier_sessions_v149 s
  where s.token_hash = digest(p_session_token, 'sha256')
    and s.revoked_at is null
    and s.expires_at > now()
  limit 1;

  if v_courier_id is null then
    raise exception 'COURIER_SESSION_INVALID';
  end if;

  update public.courier_sessions_v149
  set last_seen_at = now()
  where token_hash = digest(p_session_token, 'sha256');

  return v_courier_id;
end;
$$;

revoke all on function private.require_courier_session_v149(text)
  from public, anon, authenticated;

create or replace function public.courier_login_v149(p_identity text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_courier_json jsonb;
  v_courier_id text;
  v_stored_password text;
  v_password_ok boolean := false;
  v_token text;
  v_expires_at timestamptz := now() + interval '8 hours';
  v_identity_normalized text;
  v_identity_hash bytea;
  v_failed_attempts integer;
begin
  if trim(coalesce(p_identity, '')) = '' or coalesce(p_password, '') = '' then
    return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_FIELDS_REQUIRED');
  end if;

  v_identity_normalized := lower(trim(p_identity));
  v_identity_hash := digest(v_identity_normalized, 'sha256');
  perform pg_advisory_xact_lock(hashtextextended(encode(v_identity_hash, 'hex'), 149));

  delete from public.courier_login_attempts_v149
  where attempted_at < now() - interval '24 hours';

  select count(*)::integer into v_failed_attempts
  from public.courier_login_attempts_v149 a
  where a.identity_hash = v_identity_hash
    and a.attempted_at >= now() - interval '15 minutes';

  if v_failed_attempts >= 5 then
    return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_RATE_LIMITED', 'retry_after_seconds', 900);
  end if;

  select to_jsonb(e) into v_courier_json
  from public.couriers e
  where trim(coalesce(to_jsonb(e) ->> 'phone', '')) = trim(p_identity)
     or lower(trim(coalesce(to_jsonb(e) ->> 'code', ''))) = v_identity_normalized
     or lower(trim(coalesce(to_jsonb(e) ->> 'courier_code', ''))) = v_identity_normalized
     or lower(trim(coalesce(to_jsonb(e) ->> 'email', ''))) = v_identity_normalized
  limit 1;

  v_courier_id := coalesce(v_courier_json ->> 'id', '');
  if v_courier_id = '' then
    insert into public.courier_login_attempts_v149(identity_hash) values (v_identity_hash);
    if v_failed_attempts + 1 >= 5 then
      return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_RATE_LIMITED', 'retry_after_seconds', 900);
    end if;
    return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_INVALID');
  end if;

  if lower(coalesce(v_courier_json ->> 'is_active', 'true')) in ('false', '0')
     or lower(coalesce(v_courier_json ->> 'active', 'true')) in ('false', '0')
     or lower(coalesce(v_courier_json ->> 'disabled', 'false')) in ('true', '1') then
    return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_DISABLED');
  end if;

  v_stored_password := coalesce(v_courier_json ->> 'password', '');
  if v_stored_password ~ '^\$2[aby]\$' then
    begin
      v_password_ok := crypt(p_password, v_stored_password) = v_stored_password;
    exception when others then
      v_password_ok := false;
    end;
  elsif v_stored_password = p_password then
    v_password_ok := true;
  end if;

  if not v_password_ok then
    insert into public.courier_login_attempts_v149(identity_hash) values (v_identity_hash);
    if v_failed_attempts + 1 >= 5 then
      return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_RATE_LIMITED', 'retry_after_seconds', 900);
    end if;
    return jsonb_build_object('ok', false, 'error', 'COURIER_LOGIN_INVALID');
  end if;

  delete from public.courier_login_attempts_v149 where identity_hash = v_identity_hash;
  delete from public.courier_sessions_v149
  where courier_id = v_courier_id and (expires_at <= now() or revoked_at is not null);

  v_token := encode(gen_random_bytes(32), 'hex');
  insert into public.courier_sessions_v149(courier_id, token_hash, expires_at)
  values (v_courier_id, digest(v_token, 'sha256'), v_expires_at);

  return jsonb_build_object(
    'ok', true,
    'session_token', v_token,
    'expires_at', v_expires_at,
    'courier', jsonb_strip_nulls(jsonb_build_object(
      'id', v_courier_id,
      'name', v_courier_json ->> 'name',
      'courier_name', v_courier_json ->> 'courier_name',
      'code', v_courier_json ->> 'code',
      'courier_code', v_courier_json ->> 'courier_code',
      'phone', v_courier_json ->> 'phone',
      'branch_id', v_courier_json ->> 'branch_id',
      'branch_uuid', v_courier_json ->> 'branch_uuid',
      'delivery_agent_id', v_courier_json ->> 'delivery_agent_id',
      'uuid', v_courier_json ->> 'uuid',
      'user_id', v_courier_json ->> 'user_id',
      'courier_uuid', v_courier_json ->> 'courier_uuid',
      'legacy_id', v_courier_json ->> 'legacy_id',
      'permissions', v_courier_json -> 'permissions'
    ))
  );
end;
$$;

revoke all on function public.courier_login_v149(text, text) from public;
grant execute on function public.courier_login_v149(text, text) to anon, authenticated;

create or replace function public.courier_session_identity_v149(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_courier_id text;
  v_courier_json jsonb;
begin
  v_courier_id := private.require_courier_session_v149(p_session_token);

  select to_jsonb(e) into v_courier_json
  from public.couriers e
  where e.id::text = v_courier_id
  limit 1;

  if v_courier_json is null then raise exception 'COURIER_SESSION_ACTOR_NOT_FOUND'; end if;
  if lower(coalesce(v_courier_json ->> 'is_active', 'true')) in ('false', '0')
     or lower(coalesce(v_courier_json ->> 'active', 'true')) in ('false', '0')
     or lower(coalesce(v_courier_json ->> 'disabled', 'false')) in ('true', '1') then
    raise exception 'COURIER_SESSION_ACTOR_DISABLED';
  end if;

  return jsonb_build_object('ok', true, 'courier', jsonb_strip_nulls(jsonb_build_object(
    'id', v_courier_json ->> 'id',
    'name', v_courier_json ->> 'name',
    'courier_name', v_courier_json ->> 'courier_name',
    'code', v_courier_json ->> 'code',
    'courier_code', v_courier_json ->> 'courier_code',
    'phone', v_courier_json ->> 'phone',
    'branch_id', v_courier_json ->> 'branch_id',
    'branch_uuid', v_courier_json ->> 'branch_uuid',
    'delivery_agent_id', v_courier_json ->> 'delivery_agent_id',
    'uuid', v_courier_json ->> 'uuid',
    'user_id', v_courier_json ->> 'user_id',
    'courier_uuid', v_courier_json ->> 'courier_uuid',
    'legacy_id', v_courier_json ->> 'legacy_id',
    'permissions', v_courier_json -> 'permissions'
  )));
end;
$$;

revoke all on function public.courier_session_identity_v149(text) from public;
grant execute on function public.courier_session_identity_v149(text) to anon, authenticated;

create or replace function public.courier_logout_v149(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
begin
  update public.courier_sessions_v149
  set revoked_at = now()
  where token_hash = digest(coalesce(p_session_token, ''), 'sha256') and revoked_at is null;
  return found;
end;
$$;

revoke all on function public.courier_logout_v149(text) from public;
grant execute on function public.courier_logout_v149(text) to anon, authenticated;

commit;
