-- MeshWar global stores: public read + admin-verified write RPCs.
create table if not exists public.global_stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  logo_url text not null default '',
  category text not null default 'comprehensive' check (category in ('comprehensive','fashion','sports','beauty','home')),
  store_url text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.global_stores enable row level security;
revoke all on table public.global_stores from anon, authenticated;
grant select on table public.global_stores to anon, authenticated;
drop policy if exists global_stores_public_read on public.global_stores;
create policy global_stores_public_read on public.global_stores for select to anon, authenticated using (true);

create or replace function public.save_global_store(p_admin_id text,p_name text,p_logo_url text,p_category text,p_store_url text,p_sort_order integer default 0)
returns bigint language plpgsql security definer set search_path=public as $$
declare v_id bigint;
begin
  if not exists (select 1 from public.employees e where e.id::text=btrim(p_admin_id) and lower(btrim(coalesce(e.role::text,''))) in ('admin','أدمن','ادمن') and coalesce(e.is_active,true)=true) then raise exception 'Not authorized to manage global stores'; end if;
  if btrim(coalesce(p_name,''))='' or btrim(coalesce(p_store_url,''))='' then raise exception 'Store name and URL are required'; end if;
  if coalesce(p_category,'') not in ('comprehensive','fashion','sports','beauty','home') then raise exception 'Invalid store category'; end if;
  insert into public.global_stores(name,logo_url,category,store_url,sort_order,is_active,updated_at) values(btrim(p_name),btrim(coalesce(p_logo_url,'')),p_category,btrim(p_store_url),coalesce(p_sort_order,0),true,now())
  on conflict(name) do update set logo_url=excluded.logo_url,category=excluded.category,store_url=excluded.store_url,sort_order=excluded.sort_order,is_active=true,updated_at=now() returning id into v_id;
  return v_id;
end;$$;

create or replace function public.delete_global_store(p_admin_id text,p_store_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not exists (select 1 from public.employees e where e.id::text=btrim(p_admin_id) and lower(btrim(coalesce(e.role::text,''))) in ('admin','أدمن','ادمن') and coalesce(e.is_active,true)=true) then raise exception 'Not authorized to manage global stores'; end if;
  delete from public.global_stores where id=p_store_id;
  return found;
end;$$;
revoke all on function public.save_global_store(text,text,text,text,text,integer) from public;
revoke all on function public.delete_global_store(text,bigint) from public;
grant execute on function public.save_global_store(text,text,text,text,text,integer) to anon, authenticated;
grant execute on function public.delete_global_store(text,bigint) to anon, authenticated;

insert into public.global_stores(name,logo_url,category,store_url,sort_order,is_active) values
('Trendyol','images/trendyol.png','comprehensive','https://www.trendyol.com',1,true),
('Hepsiburada','images/hepsiburada.png','comprehensive','https://www.hepsiburada.com',2,true),
('N11','images/N11.png','comprehensive','https://www.n11.com',3,true),
('Boyner','images/boyner.png','comprehensive','https://www.boyner.com.tr/',4,true),
('Beymen','images/beymen.png','comprehensive','https://www.beymen.com/tr/',5,true),
('LC Waikiki','images/waikiki.png','fashion','https://www.lcwaikiki.com',6,true),
('Defacto','images/defacto.png','fashion','https://www.defacto.com.tr',7,true),
('Koton','images/KOTON.png','fashion','https://www.koton.com',8,true),
('Mavi','images/mavi.png','fashion','https://www.mavi.com/',9,true),
('Colin''s','images/colins.png','fashion','https://www.colins.com.tr/',10,true),
('LTB','images/ltb.png','fashion','https://www.ltbjeans.com/',11,true),
('U.S. Polo Assn.','images/uspolo.png','fashion','https://tr.uspoloassn.com/',12,true),
('Zara','images/zara.png','fashion','https://www.zara.com/tr/',13,true),
('H&M','images/hm.png','fashion','https://www2.hm.com/tr_tr/index.html',14,true),
('Mango','images/mango.png','fashion','https://shop.mango.com/tr/tr',15,true),
('Bershka','images/bershka.png','fashion','https://www.bershka.com/tr/',16,true),
('Pull&Bear','images/pullandbear.png','fashion','https://www.pullandbear.com/tr/en/',17,true),
('Stradivarius','images/stradivarius.png','fashion','https://www.stradivarius.com/tr/',18,true),
('Oysho','images/oysho.png','fashion','https://www.oysho.com/tr/',19,true),
('Massimo Dutti','images/massimodutti.png','fashion','https://www.massimodutti.com/tr/',20,true),
('Marks & Spencer','images/marksandspencer.png','fashion','https://www.marksandspencer.com.tr/',21,true),
('İpekyol','images/ipekyol.png','fashion','https://www.ipekyol.com.tr/',22,true),
('Twist','images/twist.png','fashion','https://www.twist.com.tr/',23,true),
('D''S Damat','images/dsdamat.png','fashion','https://www.dsdamat.com/',24,true),
('Lacoste','images/lacoste.png','fashion','https://www.lacoste.com.tr/',25,true),
('Esswaap','images/esswaap.png','fashion','https://www.esswaap.com/',26,true),
('Kayra','images/kayra.png','fashion','https://www.kayra.com/',27,true),
('Nike','images/nike.png','comprehensive','https://www.nike.com/tr/',28,true),
('Adidas','images/adidas.png','comprehensive','https://www.adidas.com.tr/',29,true),
('Puma','images/puma.png','comprehensive','https://tr.puma.com/',30,true),
('FLO','images/flo.png','comprehensive','https://www.flo.com.tr/',31,true),
('SuperStep','images/superstep.png','comprehensive','https://www.superstep.com.tr/',32,true),
('Luvi Shoes','images/luvishoes.png','comprehensive','https://www.luvishoes.com/',33,true),
('Gratis','images/gratis.png','beauty','https://www.gratis.com',34,true),
('Watsons','images/watsons.png','beauty','https://www.watsons.com.tr',35,true),
('Eve Shop','images/eveshop.png','beauty','https://www.eveshop.com.tr/',36,true),
('Sephora','images/sephora.png','beauty','https://www.sephora.com.tr/',37,true),
('MAD Parfumeur','images/madparfum.png','beauty','https://www.madparfum.com/',38,true),
('Golden Rose','images/goldenrose.png','beauty','https://shop.goldenrose.com.tr/',39,true),
('Penti','images/penti.png','beauty','https://www.penti.com/tr/',40,true),
('Madame Coco','images/madamecoco.png','comprehensive','https://www.madamecoco.com/',41,true),
('English Home','images/englishhome.png','comprehensive','https://www.englishhome.com/',42,true),
('ebebek','images/ebebek.png','comprehensive','https://kurumsal.ebebek.com/',43,true),
('Kanz','images/kanz.png','comprehensive','https://www.kanzcocuk.com/',44,true),
('Toyzz Shop','images/toyzzshop.png','comprehensive','https://www.toyzzshop.com/',45,true),
('Getir','images/getir.png','comprehensive','https://getir.com/',46,true),
('Migros','images/migros.png','comprehensive','https://www.migros.com.tr/',47,true),
('A101','images/a101.png','comprehensive','https://www.a101.com.tr/',48,true),
('BİM','images/bim.png','comprehensive','https://www.bim.com.tr/',49,true),
('Şok Market','images/sok.png','comprehensive','https://kurumsal.sokmarket.com.tr/',50,true)
on conflict(name) do update set logo_url=excluded.logo_url,category=excluded.category,store_url=excluded.store_url,sort_order=excluded.sort_order,is_active=excluded.is_active,updated_at=now();
