-- MeshWar Vendor Finance / P&L V21
-- Backward compatible: every new cost field is nullable; existing rows are not recalculated.

BEGIN;

ALTER TABLE public.local_products
  ADD COLUMN IF NOT EXISTS cost_price NUMERIC(14,2) NULL;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS cost_price NUMERIC(14,2) NULL,
  ADD COLUMN IF NOT EXISTS snapshot_cost_price NUMERIC(14,2) NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'local_products_cost_price_nonnegative'
  ) THEN
    ALTER TABLE public.local_products
      ADD CONSTRAINT local_products_cost_price_nonnegative
      CHECK (cost_price IS NULL OR cost_price >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_cost_price_nonnegative'
  ) THEN
    ALTER TABLE public.orders
      ADD CONSTRAINT orders_cost_price_nonnegative
      CHECK (cost_price IS NULL OR cost_price >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_snapshot_cost_price_nonnegative'
  ) THEN
    ALTER TABLE public.orders
      ADD CONSTRAINT orders_snapshot_cost_price_nonnegative
      CHECK (snapshot_cost_price IS NULL OR snapshot_cost_price >= 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_local_products_store_cost
  ON public.local_products(store_id, cost_price);

CREATE INDEX IF NOT EXISTS idx_orders_snapshot_cost
  ON public.orders(snapshot_cost_price)
  WHERE snapshot_cost_price IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.vendor_operating_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id UUID NOT NULL REFERENCES public.local_stores(id) ON DELETE CASCADE,
  amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
  currency TEXT NULL,
  category TEXT NULL,
  note TEXT NULL,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vendor_operating_expenses_store_date
  ON public.vendor_operating_expenses(store_id, expense_date DESC);

-- Resolve the product cost without changing legacy order values.
-- Preferred key: details.product_id. Backward-compatible fallback: exact store + product name.
CREATE OR REPLACE FUNCTION public.meshwar_lock_order_cost_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_store_id UUID;
  v_product_id UUID;
  v_product_name TEXT;
  v_cost NUMERIC(14,2);
  v_status TEXT;
BEGIN
  -- Once a snapshot exists it is immutable, even if later updates try to overwrite it.
  IF TG_OP = 'UPDATE' AND OLD.snapshot_cost_price IS NOT NULL THEN
    NEW.snapshot_cost_price := OLD.snapshot_cost_price;
    RETURN NEW;
  END IF;

  v_status := lower(trim(coalesce(NEW.status, '')));
  IF v_status NOT IN ('تم التسليم', 'delivered', 'delivered_to_customer') THEN
    RETURN NEW;
  END IF;

  IF NEW.snapshot_cost_price IS NOT NULL THEN
    RETURN NEW;
  END IF;

  -- An explicit order-level cost wins when supplied by a future order flow.
  IF NEW.cost_price IS NOT NULL THEN
    NEW.snapshot_cost_price := NEW.cost_price;
    RETURN NEW;
  END IF;

  BEGIN
    v_store_id := nullif(NEW.details->>'store_id','')::UUID;
  EXCEPTION WHEN invalid_text_representation THEN
    v_store_id := NULL;
  END;

  BEGIN
    v_product_id := nullif(NEW.details->>'product_id','')::UUID;
  EXCEPTION WHEN invalid_text_representation THEN
    v_product_id := NULL;
  END;

  v_product_name := nullif(trim(NEW.details->>'product_name'), '');

  IF v_product_id IS NOT NULL THEN
    SELECT p.cost_price INTO v_cost
    FROM public.local_products p
    WHERE p.id = v_product_id
      AND (v_store_id IS NULL OR p.store_id = v_store_id)
    LIMIT 1;
  ELSIF v_store_id IS NOT NULL AND v_product_name IS NOT NULL THEN
    SELECT p.cost_price INTO v_cost
    FROM public.local_products p
    WHERE p.store_id = v_store_id
      AND p.product_name = v_product_name
    ORDER BY p.updated_at DESC NULLS LAST, p.created_at DESC NULLS LAST
    LIMIT 1;
  END IF;

  -- NULL remains NULL for legacy/unknown products; no historical values are fabricated.
  NEW.snapshot_cost_price := v_cost;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_meshwar_lock_order_cost_snapshot ON public.orders;
CREATE TRIGGER trg_meshwar_lock_order_cost_snapshot
BEFORE INSERT OR UPDATE OF status, cost_price, snapshot_cost_price, details
ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.meshwar_lock_order_cost_snapshot();

COMMIT;
