-- MeshWar Vendor Financial Periods V24
-- Non-destructive accounting close: rows are marked settled, never deleted.
BEGIN;

CREATE TABLE IF NOT EXISTS public.vendor_financial_settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id TEXT NOT NULL,
  period_no INTEGER NOT NULL,
  started_at TIMESTAMPTZ NULL,
  closed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  note TEXT NULL,
  currency TEXT NULL,
  sales_total NUMERIC(16,2) NOT NULL DEFAULT 0,
  cogs_total NUMERIC(16,2) NOT NULL DEFAULT 0,
  fees_total NUMERIC(16,2) NOT NULL DEFAULT 0,
  expenses_total NUMERIC(16,2) NOT NULL DEFAULT 0,
  net_total NUMERIC(16,2) NOT NULL DEFAULT 0,
  order_count INTEGER NOT NULL DEFAULT 0,
  expense_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(store_id, period_no)
);

ALTER TABLE public.vendor_operating_expenses
  ADD COLUMN IF NOT EXISTS settlement_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS settled_at TIMESTAMPTZ NULL;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS vendor_settlement_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS vendor_settled_at TIMESTAMPTZ NULL;

CREATE INDEX IF NOT EXISTS idx_vendor_settlements_store_closed
  ON public.vendor_financial_settlements(store_id, closed_at DESC);
CREATE INDEX IF NOT EXISTS idx_vendor_expenses_settlement
  ON public.vendor_operating_expenses(store_id, settlement_id);
CREATE INDEX IF NOT EXISTS idx_orders_vendor_settlement
  ON public.orders(vendor_settlement_id);

CREATE OR REPLACE FUNCTION public.vendor_get_financial_periods(p_store_id TEXT)
RETURNS SETOF public.vendor_financial_settlements
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.*
  FROM public.vendor_financial_settlements s
  WHERE s.store_id = btrim(p_store_id)
  ORDER BY s.period_no DESC, s.closed_at DESC;
$$;

CREATE OR REPLACE FUNCTION public.vendor_close_financial_period(
  p_store_id TEXT,
  p_note TEXT DEFAULT NULL,
  p_currency TEXT DEFAULT NULL
)
RETURNS public.vendor_financial_settlements
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_settlement public.vendor_financial_settlements;
  v_period_no INTEGER;
  v_started_at TIMESTAMPTZ;
  v_sales NUMERIC(16,2) := 0;
  v_cogs NUMERIC(16,2) := 0;
  v_fees NUMERIC(16,2) := 0;
  v_expenses NUMERIC(16,2) := 0;
  v_order_count INTEGER := 0;
  v_expense_count INTEGER := 0;
BEGIN
  IF p_store_id IS NULL OR btrim(p_store_id) = '' THEN
    RAISE EXCEPTION 'Store id is required';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('meshwar_vendor_settlement:' || btrim(p_store_id)));

  SELECT COALESCE(MAX(period_no),0) + 1,
         MAX(closed_at)
    INTO v_period_no, v_started_at
  FROM public.vendor_financial_settlements
  WHERE store_id = btrim(p_store_id);

  SELECT
    COALESCE(SUM(o.total_price),0),
    COALESCE(SUM(
      COALESCE(o.snapshot_cost_price,o.cost_price,0) *
      CASE WHEN COALESCE(o.details->>'quantity','') ~ '^[0-9]+([.][0-9]+)?$'
           THEN GREATEST(1,(o.details->>'quantity')::numeric) ELSE 1 END
    ),0),
    COALESCE(SUM(
      COALESCE(o.total_price,0) *
      (CASE WHEN COALESCE(o.details->>'commission_rate','') ~ '^[0-9]+([.][0-9]+)?$'
            THEN (o.details->>'commission_rate')::numeric ELSE 0 END) / 100
      + CASE WHEN COALESCE(o.details->>'vendor_other_deductions','') ~ '^-?[0-9]+([.][0-9]+)?$'
             THEN (o.details->>'vendor_other_deductions')::numeric ELSE 0 END
    ),0),
    COUNT(*)::integer
  INTO v_sales,v_cogs,v_fees,v_order_count
  FROM public.orders o
  WHERE COALESCE(o.details->>'store_id','') = btrim(p_store_id)
    AND o.vendor_settlement_id IS NULL
    AND lower(trim(COALESCE(o.status,''))) IN ('تم التسليم','delivered','delivered_to_customer');

  SELECT COALESCE(SUM(e.amount),0), COUNT(*)::integer
    INTO v_expenses,v_expense_count
  FROM public.vendor_operating_expenses e
  WHERE e.store_id = btrim(p_store_id)
    AND e.settlement_id IS NULL;

  INSERT INTO public.vendor_financial_settlements(
    store_id,period_no,started_at,note,currency,
    sales_total,cogs_total,fees_total,expenses_total,net_total,
    order_count,expense_count
  ) VALUES (
    btrim(p_store_id),v_period_no,v_started_at,NULLIF(btrim(COALESCE(p_note,'')),''),p_currency,
    v_sales,v_cogs,v_fees,v_expenses,(v_sales-v_cogs-v_fees-v_expenses),
    v_order_count,v_expense_count
  ) RETURNING * INTO v_settlement;

  UPDATE public.orders o
     SET vendor_settlement_id = v_settlement.id,
         vendor_settled_at = v_settlement.closed_at
   WHERE COALESCE(o.details->>'store_id','') = btrim(p_store_id)
     AND o.vendor_settlement_id IS NULL
     AND lower(trim(COALESCE(o.status,''))) IN ('تم التسليم','delivered','delivered_to_customer');

  UPDATE public.vendor_operating_expenses e
     SET settlement_id = v_settlement.id,
         settled_at = v_settlement.closed_at,
         updated_at = NOW()
   WHERE e.store_id = btrim(p_store_id)
     AND e.settlement_id IS NULL;

  RETURN v_settlement;
END;
$$;

REVOKE ALL ON FUNCTION public.vendor_get_financial_periods(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.vendor_close_financial_period(TEXT,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.vendor_get_financial_periods(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.vendor_close_financial_period(TEXT,TEXT,TEXT) TO anon, authenticated;

COMMIT;
