-- KINTO V143 / phase 2A
-- Additive verified employee sessions. Does not alter employees, orders, messages,
-- invoices, statuses, storage, or any existing policy/function.

begin;

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.employee_sessions_v143 (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null,
  token_hash bytea not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists employee_sessions_v143_actor_active_idx
  on public.employee_sessions_v143(employee_id, expires_at desc)
  where revoked_at is null;

alter table public.employee_sessions_v143 enable row level security;
revoke all on table public.employee_sessions_v143 from public, anon, authenticated;

create table if not exists public.employee_login_attempts_v143 (
  id bigint generated by default as identity primary key,
  identity_hash bytea not null,
  attempted_at timestamptz not null default now()
);

create index if not exists employee_login_attempts_v143_identity_time_idx
  on public.employee_login_attempts_v143(identity_hash, attempted_at desc);

alter table public.employee_login_attempts_v143 enable row level security;
revoke all on table public.employee_login_attempts_v143 from public, anon, authenticated;

create or replace function private.require_employee_session_v143(p_session_token text)
returns text
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_employee_id text;
begin
  if trim(coalesce(p_session_token, '')) = '' then
    raise exception 'EMPLOYEE_SESSION_REQUIRED';
  end if;

  select s.employee_id into v_employee_id
  from public.employee_sessions_v143 s
  where s.token_hash = digest(p_session_token, 'sha256')
    and s.revoked_at is null
    and s.expires_at > now()
  limit 1;

  if v_employee_id is null then
    raise exception 'EMPLOYEE_SESSION_INVALID';
  end if;

  update public.employee_sessions_v143
  set last_seen_at = now()
  where token_hash = digest(p_session_token, 'sha256');

  return v_employee_id;
end;
$$;

revoke all on function private.require_employee_session_v143(text)
  from public, anon, authenticated;

create or replace function public.employee_login_v143(
  p_identity text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_employee_json jsonb;
  v_employee_id text;
  v_role text;
  v_stored_password text;
  v_password_ok boolean := false;
  v_active boolean := true;
  v_token text;
  v_expires_at timestamptz := now() + interval '12 hours';
  v_identity_normalized text;
  v_identity_hash bytea;
  v_failed_attempts integer;
begin
  if trim(coalesce(p_identity, '')) = '' or coalesce(p_password, '') = '' then
    return jsonb_build_object('ok', false, 'error', 'EMPLOYEE_LOGIN_FIELDS_REQUIRED');
  end if;

  v_identity_normalized := lower(trim(p_identity));
  v_identity_hash := digest(v_identity_normalized, 'sha256');

  perform pg_advisory_xact_lock(
    hashtextextended(encode(v_identity_hash, 'hex'), 143)
  );

  delete from public.employee_login_attempts_v143
  where attempted_at < now() - interval '24 hours';

  select count(*)::integer into v_failed_attempts
  from public.employee_login_attempts_v143 a
  where a.identity_hash = v_identity_hash
    and a.attempted_at >= now() - interval '15 minutes';

  if v_failed_attempts >= 5 then
    return jsonb_build_object(
      'ok', false,
      'error', 'EMPLOYEE_LOGIN_RATE_LIMITED',
      'retry_after_seconds', 900
    );
  end if;

  select to_jsonb(e) into v_employee_json
  from public.employees e
  where trim(coalesce(to_jsonb(e) ->> 'phone', '')) = trim(p_identity)
     or lower(trim(coalesce(to_jsonb(e) ->> 'code', ''))) = v_identity_normalized
     or lower(trim(coalesce(to_jsonb(e) ->> 'email', ''))) = v_identity_normalized
  limit 1;

  v_employee_id := coalesce(v_employee_json ->> 'id', '');
  v_role := lower(trim(coalesce(v_employee_json ->> 'role', '')));

  if v_employee_id = '' or v_role not in ('employee', 'موظف') then
    insert into public.employee_login_attempts_v143(identity_hash)
    values (v_identity_hash);
    return jsonb_build_object('ok', false, 'error', 'EMPLOYEE_LOGIN_INVALID');
  end if;

  if lower(coalesce(v_employee_json ->> 'is_active', 'true')) in ('false', '0')
     or lower(coalesce(v_employee_json ->> 'active', 'true')) in ('false', '0')
     or lower(coalesce(v_employee_json ->> 'disabled', 'false')) in ('true', '1') then
    v_active := false;
  end if;

  if not v_active then
    return jsonb_build_object('ok', false, 'error', 'EMPLOYEE_LOGIN_DISABLED');
  end if;

  v_stored_password := coalesce(v_employee_json ->> 'password', '');

  if v_stored_password ~ '^\$2[aby]\$' then
    begin
      v_password_ok := crypt(p_password, v_stored_password) = v_stored_password;
    exception when others then
      v_password_ok := false;
    end;
  elsif v_stored_password = p_password then
    -- Compatibility only. Plaintext migration is deferred until every role uses
    -- verified sessions and its rollback has passed.
    v_password_ok := true;
  end if;

  if not v_password_ok then
    insert into public.employee_login_attempts_v143(identity_hash)
    values (v_identity_hash);
    return jsonb_build_object('ok', false, 'error', 'EMPLOYEE_LOGIN_INVALID');
  end if;

  delete from public.employee_login_attempts_v143
  where identity_hash = v_identity_hash;

  delete from public.employee_sessions_v143
  where employee_id = v_employee_id
    and (expires_at <= now() or revoked_at is not null);

  v_token := encode(gen_random_bytes(32), 'hex');

  insert into public.employee_sessions_v143(employee_id, token_hash, expires_at)
  values (v_employee_id, digest(v_token, 'sha256'), v_expires_at);

  return jsonb_build_object(
    'ok', true,
    'session_token', v_token,
    'expires_at', v_expires_at,
    'employee', jsonb_strip_nulls(jsonb_build_object(
      'id', v_employee_id,
      'name', v_employee_json ->> 'name',
      'phone', v_employee_json ->> 'phone',
      'role', v_employee_json ->> 'role',
      'permissions', v_employee_json -> 'permissions'
    ))
  );
end;
$$;

revoke all on function public.employee_login_v143(text, text) from public;
grant execute on function public.employee_login_v143(text, text) to anon, authenticated;

create or replace function public.employee_session_identity_v143(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_employee_id text;
  v_employee_json jsonb;
begin
  v_employee_id := private.require_employee_session_v143(p_session_token);

  select to_jsonb(e) into v_employee_json
  from public.employees e
  where e.id::text = v_employee_id
  limit 1;

  if v_employee_json is null then
    raise exception 'EMPLOYEE_SESSION_ACTOR_NOT_FOUND';
  end if;

  if lower(coalesce(v_employee_json ->> 'is_active', 'true')) in ('false', '0')
     or lower(coalesce(v_employee_json ->> 'active', 'true')) in ('false', '0')
     or lower(coalesce(v_employee_json ->> 'disabled', 'false')) in ('true', '1') then
    raise exception 'EMPLOYEE_SESSION_ACTOR_DISABLED';
  end if;

  return jsonb_strip_nulls(jsonb_build_object(
    'ok', true,
    'employee', jsonb_build_object(
      'id', v_employee_json ->> 'id',
      'name', v_employee_json ->> 'name',
      'phone', v_employee_json ->> 'phone',
      'role', v_employee_json ->> 'role',
      'permissions', v_employee_json -> 'permissions'
    )
  ));
end;
$$;

revoke all on function public.employee_session_identity_v143(text) from public;
grant execute on function public.employee_session_identity_v143(text) to anon, authenticated;

create or replace function public.employee_logout_v143(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  update public.employee_sessions_v143
  set revoked_at = now()
  where token_hash = digest(coalesce(p_session_token, ''), 'sha256')
    and revoked_at is null;

  return found;
end;
$$;

revoke all on function public.employee_logout_v143(text) from public;
grant execute on function public.employee_logout_v143(text) to anon, authenticated;

commit;

