-- KINTO V148: additive verified branch sessions.
-- Does not alter branches, employees, orders, invoices, messages, customers, or existing functions.

begin;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;

create table if not exists public.branch_sessions_v148 (
  id uuid primary key default gen_random_uuid(),
  branch_id text not null,
  token_hash bytea not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists branch_sessions_v148_actor_active_idx
  on public.branch_sessions_v148(branch_id, expires_at desc)
  where revoked_at is null;

alter table public.branch_sessions_v148 enable row level security;
revoke all on table public.branch_sessions_v148 from public, anon, authenticated;

create table if not exists public.branch_login_attempts_v148 (
  id bigint generated by default as identity primary key,
  identity_hash bytea not null,
  attempted_at timestamptz not null default now()
);

create index if not exists branch_login_attempts_v148_identity_time_idx
  on public.branch_login_attempts_v148(identity_hash, attempted_at desc);

alter table public.branch_login_attempts_v148 enable row level security;
revoke all on table public.branch_login_attempts_v148 from public, anon, authenticated;

create or replace function private.require_branch_session_v148(p_session_token text)
returns text
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_branch_id text;
begin
  if trim(coalesce(p_session_token, '')) = '' then
    raise exception 'BRANCH_SESSION_REQUIRED';
  end if;

  select s.branch_id into v_branch_id
  from public.branch_sessions_v148 s
  where s.token_hash = digest(p_session_token, 'sha256')
    and s.revoked_at is null
    and s.expires_at > now()
  limit 1;

  if v_branch_id is null then
    raise exception 'BRANCH_SESSION_INVALID';
  end if;

  update public.branch_sessions_v148
  set last_seen_at = now()
  where token_hash = digest(p_session_token, 'sha256');

  return v_branch_id;
end;
$$;

revoke all on function private.require_branch_session_v148(text)
  from public, anon, authenticated;

create or replace function public.branch_login_v148(p_identity text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_branch_json jsonb;
  v_branch_id text;
  v_stored_password text;
  v_password_ok boolean := false;
  v_token text;
  v_expires_at timestamptz := now() + interval '8 hours';
  v_identity_normalized text;
  v_identity_hash bytea;
  v_failed_attempts integer;
begin
  if trim(coalesce(p_identity, '')) = '' or coalesce(p_password, '') = '' then
    return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_FIELDS_REQUIRED');
  end if;

  v_identity_normalized := lower(trim(p_identity));
  v_identity_hash := digest(v_identity_normalized, 'sha256');
  perform pg_advisory_xact_lock(hashtextextended(encode(v_identity_hash, 'hex'), 148));

  delete from public.branch_login_attempts_v148
  where attempted_at < now() - interval '24 hours';

  select count(*)::integer into v_failed_attempts
  from public.branch_login_attempts_v148 a
  where a.identity_hash = v_identity_hash
    and a.attempted_at >= now() - interval '15 minutes';

  if v_failed_attempts >= 5 then
    return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_RATE_LIMITED', 'retry_after_seconds', 900);
  end if;

  select to_jsonb(e) into v_branch_json
  from public.branches e
  where trim(coalesce(to_jsonb(e) ->> 'phone', '')) = trim(p_identity)
     or lower(trim(coalesce(to_jsonb(e) ->> 'code', ''))) = v_identity_normalized
     or lower(trim(coalesce(to_jsonb(e) ->> 'branch_code', ''))) = v_identity_normalized
     or lower(trim(coalesce(to_jsonb(e) ->> 'email', ''))) = v_identity_normalized
  limit 1;

  v_branch_id := coalesce(v_branch_json ->> 'id', '');
  if v_branch_id = '' then
    insert into public.branch_login_attempts_v148(identity_hash) values (v_identity_hash);
    if v_failed_attempts + 1 >= 5 then
      return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_RATE_LIMITED', 'retry_after_seconds', 900);
    end if;
    return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_INVALID');
  end if;

  if lower(coalesce(v_branch_json ->> 'is_active', 'true')) in ('false', '0')
     or lower(coalesce(v_branch_json ->> 'active', 'true')) in ('false', '0')
     or lower(coalesce(v_branch_json ->> 'disabled', 'false')) in ('true', '1') then
    return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_DISABLED');
  end if;

  v_stored_password := coalesce(v_branch_json ->> 'password', '');
  if v_stored_password ~ '^\$2[aby]\$' then
    begin
      v_password_ok := crypt(p_password, v_stored_password) = v_stored_password;
    exception when others then
      v_password_ok := false;
    end;
  elsif v_stored_password = p_password then
    v_password_ok := true;
  end if;

  if not v_password_ok then
    insert into public.branch_login_attempts_v148(identity_hash) values (v_identity_hash);
    if v_failed_attempts + 1 >= 5 then
      return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_RATE_LIMITED', 'retry_after_seconds', 900);
    end if;
    return jsonb_build_object('ok', false, 'error', 'BRANCH_LOGIN_INVALID');
  end if;

  delete from public.branch_login_attempts_v148 where identity_hash = v_identity_hash;
  delete from public.branch_sessions_v148
  where branch_id = v_branch_id and (expires_at <= now() or revoked_at is not null);

  v_token := encode(gen_random_bytes(32), 'hex');
  insert into public.branch_sessions_v148(branch_id, token_hash, expires_at)
  values (v_branch_id, digest(v_token, 'sha256'), v_expires_at);

  return jsonb_build_object(
    'ok', true,
    'session_token', v_token,
    'expires_at', v_expires_at,
    'branch', jsonb_strip_nulls(jsonb_build_object(
      'id', v_branch_id,
      'name', v_branch_json ->> 'name',
      'branch_name', v_branch_json ->> 'branch_name',
      'code', v_branch_json ->> 'code',
      'branch_code', v_branch_json ->> 'branch_code',
      'phone', v_branch_json ->> 'phone',
      'permissions', v_branch_json -> 'permissions'
    ))
  );
end;
$$;

revoke all on function public.branch_login_v148(text, text) from public;
grant execute on function public.branch_login_v148(text, text) to anon, authenticated;

create or replace function public.branch_session_identity_v148(p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
declare
  v_branch_id text;
  v_branch_json jsonb;
begin
  v_branch_id := private.require_branch_session_v148(p_session_token);

  select to_jsonb(e) into v_branch_json
  from public.branches e
  where e.id::text = v_branch_id
  limit 1;

  if v_branch_json is null then raise exception 'BRANCH_SESSION_ACTOR_NOT_FOUND'; end if;
  if lower(coalesce(v_branch_json ->> 'is_active', 'true')) in ('false', '0')
     or lower(coalesce(v_branch_json ->> 'active', 'true')) in ('false', '0')
     or lower(coalesce(v_branch_json ->> 'disabled', 'false')) in ('true', '1') then
    raise exception 'BRANCH_SESSION_ACTOR_DISABLED';
  end if;

  return jsonb_build_object('ok', true, 'branch', jsonb_strip_nulls(jsonb_build_object(
    'id', v_branch_json ->> 'id',
    'name', v_branch_json ->> 'name',
    'branch_name', v_branch_json ->> 'branch_name',
    'code', v_branch_json ->> 'code',
    'branch_code', v_branch_json ->> 'branch_code',
    'phone', v_branch_json ->> 'phone',
    'permissions', v_branch_json -> 'permissions'
  )));
end;
$$;

revoke all on function public.branch_session_identity_v148(text) from public;
grant execute on function public.branch_session_identity_v148(text) to anon, authenticated;

create or replace function public.branch_logout_v148(p_session_token text)
returns boolean
language plpgsql
security definer
set search_path = public, private, extensions, pg_temp
as $$
begin
  update public.branch_sessions_v148
  set revoked_at = now()
  where token_hash = digest(coalesce(p_session_token, ''), 'sha256') and revoked_at is null;
  return found;
end;
$$;

revoke all on function public.branch_logout_v148(text) from public;
grant execute on function public.branch_logout_v148(text) to anon, authenticated;

commit;
