-- MeshWar: idempotent global_stores + RPC refresh for Supabase/PostgREST schema cache.
create table if not exists public.global_stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  logo_url text not null default '',
  category text not null default 'comprehensive' check (category in ('comprehensive','fashion','sports','beauty','home')),
  store_url text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.global_stores enable row level security;
revoke all on table public.global_stores from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select on table public.global_stores to anon, authenticated;

drop policy if exists global_stores_public_read on public.global_stores;
create policy global_stores_public_read
on public.global_stores for select to anon, authenticated using (true);

create or replace function public.save_global_store(
  p_admin_id text,
  p_name text,
  p_logo_url text,
  p_category text,
  p_store_url text,
  p_sort_order integer default 0
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if not exists (
    select 1
    from public.employees e
    where e.id::text = btrim(p_admin_id)
      and lower(btrim(coalesce(e.role::text,''))) in ('admin','أدمن','ادمن')
      and coalesce(e.is_active,true) = true
  ) then
    raise exception 'Not authorized to manage global stores';
  end if;

  if btrim(coalesce(p_name,'')) = '' or btrim(coalesce(p_store_url,'')) = '' then
    raise exception 'Store name and URL are required';
  end if;

  if coalesce(p_category,'') not in ('comprehensive','fashion','sports','beauty','home') then
    raise exception 'Invalid store category';
  end if;

  insert into public.global_stores(name,logo_url,category,store_url,sort_order,is_active,updated_at)
  values(
    btrim(p_name),
    btrim(coalesce(p_logo_url,'')),
    p_category,
    btrim(p_store_url),
    coalesce(p_sort_order,0),
    true,
    now()
  )
  on conflict(name) do update set
    logo_url = excluded.logo_url,
    category = excluded.category,
    store_url = excluded.store_url,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.delete_global_store(
  p_admin_id text,
  p_store_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.employees e
    where e.id::text = btrim(p_admin_id)
      and lower(btrim(coalesce(e.role::text,''))) in ('admin','أدمن','ادمن')
      and coalesce(e.is_active,true) = true
  ) then
    raise exception 'Not authorized to manage global stores';
  end if;

  delete from public.global_stores where id = p_store_id;
  return found;
end;
$$;

revoke all on function public.save_global_store(text,text,text,text,text,integer) from public;
revoke all on function public.delete_global_store(text,bigint) from public;
grant execute on function public.save_global_store(text,text,text,text,text,integer) to anon, authenticated;
grant execute on function public.delete_global_store(text,bigint) to anon, authenticated;

-- Ask PostgREST/Supabase API to reload its schema cache immediately.
notify pgrst, 'reload schema';
